2019-12-02 00:01:45.038 [error] <0.2329.0> gen_server <0.2329.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:01:45.038 [error] <0.2329.0> CRASH REPORT Process <0.2329.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:01:45.038 [error] <0.2325.0> gen_server <0.2325.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:01:45.040 [error] <0.2324.0> Supervisor {<0.2324.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.320>, <0.2325.0>, <0.2327.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60053 -> 127.0.0.1:5672">>) at <0.2329.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:01:45.040 [error] <0.2324.0> Supervisor {<0.2324.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.320>, <0.2325.0>, <0.2327.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60053 -> 127.0.0.1:5672">>) at <0.2329.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:01:45.040 [error] <0.2325.0> CRASH REPORT Process <0.2325.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:01:45.041 [error] <0.2323.0> Supervisor {<0.2323.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2324.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2325.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:01:45.042 [error] <0.2323.0> Supervisor {<0.2323.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2324.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2325.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:01:45.042 [error] <0.2320.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:01:45.042 [error] <0.2320.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:01:45.043 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2320.0> exit with reason no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 00:01:46.010 [warning] <0.387.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 00:55:51.027 [error] <0.2350.0> gen_server <0.2350.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:55:51.027 [error] <0.2350.0> CRASH REPORT Process <0.2350.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:55:51.027 [error] <0.2346.0> gen_server <0.2346.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:55:51.028 [error] <0.2345.0> Supervisor {<0.2345.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.321>, <0.2346.0>, <0.2348.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60100 -> 127.0.0.1:5672">>) at <0.2350.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:55:51.028 [error] <0.2345.0> Supervisor {<0.2345.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.321>, <0.2346.0>, <0.2348.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60100 -> 127.0.0.1:5672">>) at <0.2350.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:55:51.029 [error] <0.2346.0> CRASH REPORT Process <0.2346.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:55:51.030 [error] <0.2341.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:55:51.044 [error] <0.2341.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:55:51.044 [error] <0.2344.0> Supervisor {<0.2344.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2345.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2346.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:55:51.044 [error] <0.2344.0> Supervisor {<0.2344.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2345.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2346.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:55:51.044 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2341.0> exit with reason no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 01:49:57.042 [error] <0.2378.0> gen_server <0.2378.0> terminated with reason: {socket_error,timeout}
2019-12-02 01:49:57.042 [error] <0.2378.0> CRASH REPORT Process <0.2378.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 01:49:57.043 [error] <0.2373.0> gen_server <0.2373.0> terminated with reason: {socket_error,timeout}
2019-12-02 01:49:57.043 [error] <0.2372.0> Supervisor {<0.2372.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.322>, <0.2373.0>, <0.2376.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60142 -> 127.0.0.1:5672">>) at <0.2378.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 01:49:57.044 [error] <0.2372.0> Supervisor {<0.2372.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.322>, <0.2373.0>, <0.2376.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60142 -> 127.0.0.1:5672">>) at <0.2378.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 01:49:57.044 [error] <0.2373.0> CRASH REPORT Process <0.2373.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 01:49:57.045 [error] <0.2368.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 01:49:57.045 [error] <0.2368.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2372.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2373.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2372.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2373.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.2372.0> exit with reason shutdown in context shutdown_error
2019-12-02 01:49:57.054 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2368.0> exit with reason no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 01:49:58.005 [warning] <0.387.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 02:31:06.037 [error] <0.2400.0> gen_server <0.2400.0> terminated with reason: {socket_error,timeout}
2019-12-02 02:31:06.037 [error] <0.2400.0> CRASH REPORT Process <0.2400.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 02:31:06.037 [error] <0.2395.0> gen_server <0.2395.0> terminated with reason: {socket_error,timeout}
2019-12-02 02:31:06.040 [error] <0.2394.0> Supervisor {<0.2394.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.323>, <0.2395.0>, <0.2398.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60193 -> 127.0.0.1:5672">>) at <0.2400.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 02:31:06.041 [error] <0.2394.0> Supervisor {<0.2394.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.323>, <0.2395.0>, <0.2398.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60193 -> 127.0.0.1:5672">>) at <0.2400.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 02:31:06.041 [error] <0.2395.0> CRASH REPORT Process <0.2395.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 02:31:06.042 [error] <0.2390.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 02:31:06.059 [error] <0.2390.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 02:31:06.059 [error] <0.2393.0> Supervisor {<0.2393.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2394.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2395.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 02:31:06.059 [error] <0.2393.0> Supervisor {<0.2393.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2394.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2395.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 02:31:06.059 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2390.0> exit with reason no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 03:25:12.046 [error] <0.2422.0> gen_server <0.2422.0> terminated with reason: {socket_error,timeout}
2019-12-02 03:25:12.046 [error] <0.2422.0> CRASH REPORT Process <0.2422.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 03:25:12.047 [error] <0.2417.0> Supervisor {<0.2417.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.324>, <0.2418.0>, <0.2420.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60246 -> 127.0.0.1:5672">>) at <0.2422.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 03:25:12.047 [error] <0.2417.0> Supervisor {<0.2417.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.324>, <0.2418.0>, <0.2420.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60246 -> 127.0.0.1:5672">>) at <0.2422.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 03:25:12.047 [error] <0.2418.0> gen_server <0.2418.0> terminated with reason: {socket_error,timeout}
2019-12-02 03:25:12.047 [error] <0.2418.0> CRASH REPORT Process <0.2418.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 03:25:12.047 [error] <0.2413.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 03:25:12.048 [error] <0.2416.0> Supervisor {<0.2416.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2417.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2418.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 03:25:12.048 [error] <0.2416.0> Supervisor {<0.2416.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2417.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2418.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 03:25:12.048 [error] <0.2413.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 03:25:12.049 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2413.0> exit with reason no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 03:25:13.000 [warning] <0.387.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 04:19:18.031 [error] <0.2444.0> gen_server <0.2444.0> terminated with reason: {socket_error,timeout}
2019-12-02 04:19:18.031 [error] <0.2444.0> CRASH REPORT Process <0.2444.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 04:19:18.031 [error] <0.2440.0> gen_server <0.2440.0> terminated with reason: {socket_error,timeout}
2019-12-02 04:19:18.032 [error] <0.2439.0> Supervisor {<0.2439.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.325>, <0.2440.0>, <0.2442.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60304 -> 127.0.0.1:5672">>) at <0.2444.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 04:19:18.032 [error] <0.2439.0> Supervisor {<0.2439.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.325>, <0.2440.0>, <0.2442.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60304 -> 127.0.0.1:5672">>) at <0.2444.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 04:19:18.032 [error] <0.2440.0> CRASH REPORT Process <0.2440.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 04:19:18.034 [error] <0.2435.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 04:19:18.044 [error] <0.2435.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 04:19:18.045 [error] <0.2438.0> Supervisor {<0.2438.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2439.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2440.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 04:19:18.045 [error] <0.2438.0> Supervisor {<0.2438.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2439.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2440.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 04:19:18.045 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2435.0> exit with reason no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 05:13:24.048 [error] <0.2466.0> gen_server <0.2466.0> terminated with reason: {socket_error,timeout}
2019-12-02 05:13:24.048 [error] <0.2466.0> CRASH REPORT Process <0.2466.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 05:13:24.048 [error] <0.2461.0> gen_server <0.2461.0> terminated with reason: {socket_error,timeout}
2019-12-02 05:13:24.049 [error] <0.2460.0> Supervisor {<0.2460.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.326>, <0.2461.0>, <0.2464.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60362 -> 127.0.0.1:5672">>) at <0.2466.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 05:13:24.049 [error] <0.2460.0> Supervisor {<0.2460.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.326>, <0.2461.0>, <0.2464.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60362 -> 127.0.0.1:5672">>) at <0.2466.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 05:13:24.049 [error] <0.2461.0> CRASH REPORT Process <0.2461.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 05:13:24.049 [error] <0.2456.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 05:13:24.050 [error] <0.2456.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2460.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2461.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2460.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2461.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.2460.0> exit with reason shutdown in context shutdown_error
2019-12-02 05:13:24.051 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2456.0> exit with reason no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 05:13:25.014 [warning] <0.387.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 06:07:30.045 [error] <0.2488.0> gen_server <0.2488.0> terminated with reason: {socket_error,timeout}
2019-12-02 06:07:30.045 [error] <0.2488.0> CRASH REPORT Process <0.2488.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 06:07:30.045 [error] <0.2484.0> gen_server <0.2484.0> terminated with reason: {socket_error,timeout}
2019-12-02 06:07:30.046 [error] <0.2484.0> CRASH REPORT Process <0.2484.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 06:07:30.046 [error] <0.2483.0> Supervisor {<0.2483.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.327>, <0.2484.0>, <0.2486.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60423 -> 127.0.0.1:5672">>) at <0.2488.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 06:07:30.046 [error] <0.2483.0> Supervisor {<0.2483.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.327>, <0.2484.0>, <0.2486.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60423 -> 127.0.0.1:5672">>) at <0.2488.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 06:07:30.046 [error] <0.2482.0> Supervisor {<0.2482.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2483.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2484.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 06:07:30.046 [error] <0.2482.0> Supervisor {<0.2482.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2483.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2484.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 06:07:30.047 [error] <0.2479.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 06:07:30.048 [error] <0.2479.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 06:07:30.048 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2479.0> exit with reason no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:01:36.033 [error] <0.2510.0> gen_server <0.2510.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:01:36.033 [error] <0.2510.0> CRASH REPORT Process <0.2510.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:01:36.033 [error] <0.2505.0> gen_server <0.2505.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:01:36.034 [error] <0.2504.0> Supervisor {<0.2504.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.328>, <0.2505.0>, <0.2508.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60488 -> 127.0.0.1:5672">>) at <0.2510.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:01:36.034 [error] <0.2504.0> Supervisor {<0.2504.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.328>, <0.2505.0>, <0.2508.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60488 -> 127.0.0.1:5672">>) at <0.2510.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:01:36.034 [error] <0.2505.0> CRASH REPORT Process <0.2505.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:01:36.036 [error] <0.2500.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:01:36.045 [error] <0.2503.0> Supervisor {<0.2503.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2504.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2505.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:01:36.045 [error] <0.2503.0> Supervisor {<0.2503.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2504.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2505.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:01:36.045 [error] <0.2500.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:01:36.046 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2500.0> exit with reason no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:01:37.000 [warning] <0.387.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 07:25:58.032 [error] <0.2532.0> gen_server <0.2532.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:25:58.032 [error] <0.2532.0> CRASH REPORT Process <0.2532.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:25:58.032 [error] <0.2528.0> gen_server <0.2528.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:25:58.033 [error] <0.2528.0> CRASH REPORT Process <0.2528.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:25:58.045 [error] <0.2527.0> Supervisor {<0.2527.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.329>, <0.2528.0>, <0.2530.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60525 -> 127.0.0.1:5672">>) at <0.2532.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:25:58.045 [error] <0.2527.0> Supervisor {<0.2527.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.329>, <0.2528.0>, <0.2530.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60525 -> 127.0.0.1:5672">>) at <0.2532.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:25:58.045 [error] <0.2526.0> Supervisor {<0.2526.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2527.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2528.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:25:58.045 [error] <0.2526.0> Supervisor {<0.2526.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2527.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2528.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:25:58.047 [error] <0.2523.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:25:58.047 [error] <0.2523.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:25:58.048 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2523.0> exit with reason no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:35:08.494 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-02 07:35:08.503 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-02 07:35:08.508 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-02 07:35:08.515 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-02 07:35:08.517 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-02 07:35:08.517 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-02 07:35:08.525 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-02 07:35:08.527 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-02 07:35:08.532 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-02 07:35:08.536 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-02 07:35:08.542 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-02 07:35:08.551 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-02 07:35:08.555 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-02 07:35:08.568 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-02 07:35:08.574 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-02 07:35:08.577 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-02 07:35:08.582 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-02 07:35:08.588 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-02 07:35:09.014 [warning] <0.375.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 07:35:09.150 [error] <0.556.0> gen_server <0.556.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599
2019-12-02 07:35:09.163 [error] <0.556.0> CRASH REPORT Process <0.556.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599
2019-12-02 07:35:09.163 [error] <0.434.0> Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.556.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599 in context child_terminated
2019-12-02 07:40:54.700 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-02 07:40:54.708 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-02 07:40:54.712 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-02 07:40:54.719 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-02 07:40:54.722 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-02 07:40:54.722 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-02 07:40:54.728 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-02 07:40:54.730 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-02 07:40:54.735 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-02 07:40:54.738 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-02 07:40:54.743 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-02 07:40:54.749 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-02 07:40:54.753 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-02 07:40:54.768 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-02 07:40:54.774 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-02 07:40:54.776 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-02 07:40:54.781 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-02 07:40:54.786 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-02 07:40:55.011 [warning] <0.375.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 07:40:55.341 [error] <0.560.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 gen_server <0.560.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122
2019-12-02 07:40:55.356 [error] <0.560.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 CRASH REPORT Process <0.560.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122
2019-12-02 07:40:55.357 [error] <0.434.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.560.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122 in context child_terminated
2019-12-03 15:53:27.162 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-03 15:53:27.176 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-03 15:53:27.182 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-03 15:53:27.192 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-03 15:53:27.195 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-03 15:53:27.195 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-03 15:53:27.208 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-03 15:53:27.214 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-03 15:53:27.221 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-03 15:53:27.228 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-03 15:53:27.234 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-03 15:53:27.244 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-03 15:53:27.250 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-03 15:53:27.268 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-03 15:53:27.279 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-03 15:53:27.284 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-03 15:53:27.300 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-12-03 15:53:27.351 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-12-03 15:53:27.360 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-03 15:53:27.369 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-03 15:53:28.000 [warning] <0.421.0> lager_error_logger_h dropped 142 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-03 15:53:34.533 [error] <0.675.0> CRASH REPORT Process <0.675.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 15:53:34.686 [error] <0.423.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.660.0>,6,<0.675.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 15:53:38.728 [error] <0.690.0> CRASH REPORT Process <0.690.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 15:53:38.737 [error] <0.423.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.660.0>,8,<0.690.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 15:54:27.554 [error] <0.730.0> CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 15:54:27.561 [error] <0.423.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.729.0>,1,<0.730.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 15:54:46.095 [error] <0.757.0> CRASH REPORT Process <0.757.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 15:54:46.102 [error] <0.423.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.756.0>,1,<0.757.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 15:55:39.916 [error] <0.787.0> CRASH REPORT Process <0.787.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 15:55:39.939 [error] <0.423.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.785.0>,1,<0.787.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 15:56:31.008 [error] <0.815.0> CRASH REPORT Process <0.815.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 15:56:31.068 [error] <0.423.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.813.0>,1,<0.815.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:id, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 15:57:35.169 [error] <0.839.0> CRASH REPORT Process <0.839.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @view not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:search, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 15:57:35.183 [error] <0.423.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.837.0>,1,<0.839.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @view not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:search, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 16:07:44.831 [error] <0.905.0> CRASH REPORT Process <0.905.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"a component RailwayUiWeb.MessageLive.SearchComponent that has implemented handle_event/3 or preload/1 requires an :id assign to be given">>},[{'Elixir.Phoenix.LiveView','__live_component__',3,[{file,"lib/phoenix_live_view.ex"},{line,1156}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},{line,5}]},{'Elixir.Phoenix.LiveView.Utils',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:07:44.835 [error] <0.423.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.903.0>,1,<0.905.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"a component RailwayUiWeb.MessageLive.SearchComponent that has implemented handle_event/3 or preload/1 requires an :id assign to be given">>},[{'Elixir.Phoenix.LiveView','__live_component__',3,[{file,"lib/phoenix_live_view.ex"},{line,1156}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templ..."},...]},...]},...},...]},...}}
2019-12-03 16:11:56.636 [error] <0.1168.0> gen_server <0.1168.0> terminated with reason: {'module could not be loaded',[{'Elixir.Routes',live_path,[#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{search => #{'__struct__' => 'Elixir.RailwayUiWeb.MessageLive.Index.Search',query => <<"uuid">>,value => <<"79c17648-6cac-484a-911c-184b6be71bfa">>},view => 'Elixir.RailwayUiWeb.PublishedMessageLive.Index'},changed => #{},'connected?' => true,endpoint => 'Elixir.RailwayUiWeb.Endpoint',fingerprints => {92662450738149487445429617559069288610,#{}},id => <<"phx-tMTlmH4x">>,...},...],...},...]}
2019-12-03 16:11:56.656 [error] <0.1168.0>@Elixir.Routes:live_path CRASH REPORT Process <0.1168.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.Routes':live_path(#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{search => #{'__struct__' => 'Elixir.RailwayUiWeb.MessageLive.Index.Search',...},...},...}, 'Elixir.RailwayUiWeb.MessageLive.SearchComponent', #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"79c17648-6cac-484a-911c-184b6be7...">>}})
2019-12-03 16:11:56.657 [error] <0.545.0>@Elixir.Routes:live_path Supervisor {<0.545.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1168.0> exit with reason call to undefined function 'Elixir.Routes':live_path(#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{search => #{'__struct__' => 'Elixir.RailwayUiWeb.MessageLive.Index.Search',...},...},...}, 'Elixir.RailwayUiWeb.MessageLive.SearchComponent', #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"79c17648-6cac-484a-911c-184b6be7...">>}}) in context child_terminated
2019-12-03 16:12:28.791 [error] <0.1200.0> gen_server <0.1200.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/3 and action RailwayUiWeb.MessageLive.SearchComponent. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.ConsumedMessageLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, RailwayUiWeb.PublishedMessageLive.Index, params \\\\ [])">>} in 'Elixir.Phoenix.Router.Helpers':raise_route_error/6 line 346
2019-12-03 16:12:28.793 [error] <0.1200.0> CRASH REPORT Process <0.1200.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/3 and action RailwayUiWeb.MessageLive.SearchComponent. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.ConsumedMessageLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, RailwayUiWeb.PublishedMessageLive.Index, params \\\\ [])">>} in 'Elixir.Phoenix.Router.Helpers':raise_route_error/6 line 346
2019-12-03 16:12:28.793 [error] <0.546.0> Supervisor {<0.546.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1200.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/3 and action RailwayUiWeb.MessageLive.SearchComponent. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.ConsumedMessageLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, RailwayUiWeb.PublishedMessageLive.Index, params \\\\ [])">>} in 'Elixir.Phoenix.Router.Helpers':raise_route_error/6 line 346 in context child_terminated
2019-12-03 16:12:51.896 [error] <0.1233.0> gen_server <0.1233.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot redirect from from RailwayUiWeb.MessageLive.SearchComponent.handle_event/3">>} in 'Elixir.Phoenix.LiveView.Channel':'-component_handle_event/5-fun-0-'/4 line 289
2019-12-03 16:12:51.897 [error] <0.1233.0> CRASH REPORT Process <0.1233.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot redirect from from RailwayUiWeb.MessageLive.SearchComponent.handle_event/3">>} in 'Elixir.Phoenix.LiveView.Channel':'-component_handle_event/5-fun-0-'/4 line 289
2019-12-03 16:12:51.897 [error] <0.548.0> Supervisor {<0.548.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1233.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"cannot redirect from from RailwayUiWeb.MessageLive.SearchComponent.handle_event/3">>} in 'Elixir.Phoenix.LiveView.Channel':'-component_handle_event/5-fun-0-'/4 line 289 in context child_terminated
2019-12-03 16:14:03.436 [error] <0.1277.0> gen_server <0.1277.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from RailwayUiWeb.MessageLive.SearchComponent.handle_event/3 callback.\n\nExpected: {:noreply, %Socket{}}\nGot: {:search, %{\"search\" => %{\"query\" => \"uuid\", \"value\" => \"79c17648-6cac-484a-911c-184b6be71bfa\"}}}\n">>} in 'Elixir.Phoenix.LiveView.Channel':'-component_handle_event/5-fun-0-'/4 line 292
2019-12-03 16:14:03.437 [error] <0.1277.0> CRASH REPORT Process <0.1277.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from RailwayUiWeb.MessageLive.SearchComponent.handle_event/3 callback.\n\nExpected: {:noreply, %Socket{}}\nGot: {:search, %{\"search\" => %{\"query\" => \"uuid\", \"value\" => \"79c17648-6cac-484a-911c-184b6be71bfa\"}}}\n">>} in 'Elixir.Phoenix.LiveView.Channel':'-component_handle_event/5-fun-0-'/4 line 292
2019-12-03 16:14:03.437 [error] <0.545.0> Supervisor {<0.545.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1277.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid return from RailwayUiWeb.MessageLive.SearchComponent.handle_event/3 callback.\n\nExpected: {:noreply, %Socket{}}\nGot: {:search, %{\"search\" => %{\"query\" => \"uuid\", \"value\" => \"79c17648-6cac-484a-911c-184b6be71bfa\"}}}\n">>} in 'Elixir.Phoenix.LiveView.Channel':'-component_handle_event/5-fun-0-'/4 line 292 in context child_terminated
2019-12-03 16:14:28.377 [error] <0.1310.0>@Elixir.Phoenix.LiveView.Channel:handle_info:106 gen_server <0.1310.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_info/2 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 106
2019-12-03 16:14:28.378 [error] <0.1310.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_info CRASH REPORT Process <0.1310.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_info({search,#{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"79c17648-6cac-484a-911c-...">>}}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:14:28.379 [error] <0.545.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_info Supervisor {<0.545.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1310.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_info({search,#{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"79c17648-6cac-484a-911c-...">>}}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:34:25.080 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-03 16:34:25.102 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-03 16:34:25.107 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-03 16:34:25.115 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-03 16:34:25.118 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-03 16:34:25.118 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-03 16:34:25.142 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-03 16:34:25.146 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-03 16:34:25.152 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-03 16:34:25.156 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-03 16:34:25.163 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-03 16:34:25.174 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-03 16:34:25.178 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-03 16:34:25.200 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-03 16:34:25.215 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-03 16:34:25.218 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-03 16:34:25.238 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-12-03 16:34:25.284 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-12-03 16:34:25.291 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-03 16:34:25.308 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-03 16:34:26.000 [warning] <0.391.0> lager_error_logger_h dropped 142 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-03 16:34:27.622 [error] <0.632.0> CRASH REPORT Process <0.632.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => mount,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index'},[{'Elixir.RailwayUiWeb.MessageLive.Index',mount,[[{current_user_uuid,<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>},{view,'Elixir.RailwayUiWeb.PublishedMessageLive.Index'}],#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{},changed => #{},'connected?' => false,endpoint => 'Elixir.RailwayUiWeb.Endpoint',...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:34:27.773 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.630.0>,1,<0.632.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => mount,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index'},[{'Elixir.RailwayUiWeb.MessageLive.Index',mount,[[{current_user_uuid,<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>},{view,'Elixir.RailwayUiWeb.PublishedMessageLive.Index'}],#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',...}],...},...]},...},...]},...}}
2019-12-03 16:34:32.856 [error] <0.642.0> CRASH REPORT Process <0.642.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => mount,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index'},[{'Elixir.RailwayUiWeb.MessageLive.Index',mount,[[{current_user_uuid,<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>},{view,'Elixir.RailwayUiWeb.PublishedMessageLive.Index'}],#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{},changed => #{},'connected?' => false,endpoint => 'Elixir.RailwayUiWeb.Endpoint',...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:34:32.863 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.630.0>,4,<0.642.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => mount,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index'},[{'Elixir.RailwayUiWeb.MessageLive.Index',mount,[[{current_user_uuid,<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>},{view,'Elixir.RailwayUiWeb.PublishedMessageLive.Index'}],#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',...}],...},...]},...},...]},...}}
2019-12-03 16:34:54.991 [error] <0.652.0> CRASH REPORT Process <0.652.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => mount,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index'},[{'Elixir.RailwayUiWeb.MessageLive.Index',mount,[[{current_user_uuid,<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>},{view,'Elixir.RailwayUiWeb.PublishedMessageLive.Index'},{message_type,'Elixir.RailwayUi.PublishedMessage'}],#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{},changed => #{},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:34:54.996 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.651.0>,1,<0.652.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => mount,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index'},[{'Elixir.RailwayUiWeb.MessageLive.Index',mount,[[{current_user_uuid,<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>},{view,'Elixir.RailwayUiWeb.PublishedMessageLive.Index'},{message_type,'Elixir.RailwayUi.PublishedMessage'}],...],...},...]},...},...]},...}}
2019-12-03 16:34:56.333 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => mount,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index'},[{'Elixir.RailwayUiWeb.MessageLive.Index',mount,[[{current_user_uuid,<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>},{view,'Elixir.RailwayUiWeb.PublishedMessageLive.Index'},{message_type,'Elixir.RailwayUi.PublishedMessage'}],#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{},changed => #{},...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:34:56.340 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.651.0>,3,<0.668.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => mount,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index'},[{'Elixir.RailwayUiWeb.MessageLive.Index',mount,[[{current_user_uuid,<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>},{view,'Elixir.RailwayUiWeb.PublishedMessageLive.Index'},{message_type,'Elixir.RailwayUi.PublishedMessage'}],...],...},...]},...},...]},...}}
2019-12-03 16:35:26.276 [error] <0.694.0> CRASH REPORT Process <0.694.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"handle_params/3 is not allowed on child LiveViews, only at the root">>},[{'Elixir.Phoenix.LiveView.Static',disconnected_nested_render,6,[{file,"lib/phoenix_live_view/static.ex"},{line,182}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},{line,1}]},{'Elixir.Phoenix.LiveView.Utils',to_rendered,2,[{file,"lib/phoenix_live_view/ut..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:35:26.297 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.678.0>,1,<0.694.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"handle_params/3 is not allowed on child LiveViews, only at the root">>},[{'Elixir.Phoenix.LiveView.Static',disconnected_nested_render,6,[{file,"lib/phoenix_live_view/static.ex"},{line,182}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},{line,1}]},...]},...},...]},...}}
2019-12-03 16:36:06.111 [error] <0.705.0> CRASH REPORT Process <0.705.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"handle_params/3 is not allowed on child LiveViews, only at the root">>},[{'Elixir.Phoenix.LiveView.Static',disconnected_nested_render,6,[{file,"lib/phoenix_live_view/static.ex"},{line,182}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},{line,1}]},{'Elixir.Phoenix.LiveView.Utils',to_rendered,2,[{file,"lib/phoenix_live_view/ut..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:36:06.118 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.703.0>,1,<0.705.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"handle_params/3 is not allowed on child LiveViews, only at the root">>},[{'Elixir.Phoenix.LiveView.Static',disconnected_nested_render,6,[{file,"lib/phoenix_live_view/static.ex"},{line,182}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},{line,1}]},...]},...},...]},...}}
2019-12-03 16:36:26.236 [error] <0.716.0> CRASH REPORT Process <0.716.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"an :id is required when rendering child LiveView. The :id must uniquely identify the child.">>},[{'Elixir.Phoenix.LiveView.Static',nested_render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,155}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},{line,1}]},{'Elixir.Phoenix.LiveView.Utils',to_rendered,2,[{file,"lib/phoenix_l..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:36:26.245 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.714.0>,1,<0.716.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"an :id is required when rendering child LiveView. The :id must uniquely identify the child.">>},[{'Elixir.Phoenix.LiveView.Static',nested_render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,155}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},...]},...]},...},...]},...}}
2019-12-03 16:36:32.052 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"handle_params/3 is not allowed on child LiveViews, only at the root">>},[{'Elixir.Phoenix.LiveView.Static',disconnected_nested_render,6,[{file,"lib/phoenix_live_view/static.ex"},{line,182}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},{line,1}]},{'Elixir.Phoenix.LiveView.Utils',to_rendered,2,[{file,"lib/phoenix_live_view/ut..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:36:32.059 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.714.0>,6,<0.753.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"handle_params/3 is not allowed on child LiveViews, only at the root">>},[{'Elixir.Phoenix.LiveView.Static',disconnected_nested_render,6,[{file,"lib/phoenix_live_view/static.ex"},{line,182}]},{'Elixir.RailwayUiWeb.PublishedMessageView','index.html',1,[{file,"lib/railway_ui_web/templates/published_message/index.html.leex"},{line,1}]},...]},...},...]},...}}
2019-12-03 16:37:11.731 [error] <0.775.0> CRASH REPORT Process <0.775.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @state not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:current_user_uuid, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:37:11.777 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.773.0>,1,<0.775.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @state not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:current_user_uuid, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 16:37:13.841 [error] <0.791.0> CRASH REPORT Process <0.791.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @state not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:current_user_uuid, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-03 16:37:13.846 [error] <0.393.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.773.0>,3,<0.791.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @state not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:current_user_uuid, :socket, :view, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-03 16:38:10.089 [error] <0.840.0>@Elixir.Phoenix.LiveView.Channel:handle_info:106 gen_server <0.840.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_info/2 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 106
2019-12-03 16:38:10.106 [error] <0.840.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_info CRASH REPORT Process <0.840.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_info({search,#{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"79c17648-6cac-484a-911c-...">>}}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:38:10.106 [error] <0.517.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_info Supervisor {<0.517.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.840.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_info({search,#{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"79c17648-6cac-484a-911c-...">>}}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:39:43.233 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-03 16:39:43.247 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-03 16:39:43.253 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-03 16:39:43.267 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-03 16:39:43.271 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-03 16:39:43.271 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-03 16:39:43.292 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-03 16:39:43.304 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-03 16:39:43.310 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-03 16:39:43.319 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-03 16:39:43.326 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-03 16:39:43.361 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-03 16:39:43.390 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-03 16:39:43.422 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-03 16:39:43.448 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-03 16:39:43.452 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-03 16:39:43.463 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-03 16:39:43.480 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-03 16:39:44.033 [warning] <0.439.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-03 16:39:44.137 [error] <0.608.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 gen_server <0.608.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"7702af8f-ea1e-41ea-899...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:39:44.166 [error] <0.608.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 CRASH REPORT Process <0.608.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"7702af8f-ea1e-41ea-899...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:39:44.166 [error] <0.498.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.608.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"7702af8f-ea1e-41ea-899...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10 in context child_terminated
2019-12-03 16:39:44.299 [error] <0.620.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 gen_server <0.620.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"f1219f9b-92e6-4091-9747-5c1b41cc...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:39:44.300 [error] <0.620.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 CRASH REPORT Process <0.620.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"f1219f9b-92e6-4091-9747-5c1b41cc...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:39:44.300 [error] <0.498.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.620.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"f1219f9b-92e6-4091-9747-5c1b41cc...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10 in context child_terminated
2019-12-03 16:39:44.340 [error] <0.624.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 gen_server <0.624.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:39:44.340 [error] <0.624.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 CRASH REPORT Process <0.624.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:39:44.341 [error] <0.498.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.624.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10 in context child_terminated
2019-12-03 16:39:44.424 [error] <0.634.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.634.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:39:44.431 [error] <0.634.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.634.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"7636e845-5021-417f-978...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:39:44.431 [error] <0.498.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.634.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"7636e845-5021-417f-978...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:39:44.519 [error] <0.642.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.642.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:39:44.519 [error] <0.642.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.642.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"d87bfa71-7ef0-4df7-a6b8-d12d49fd...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:39:44.520 [error] <0.498.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.642.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"d87bfa71-7ef0-4df7-a6b8-d12d49fd...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:39:44.561 [error] <0.646.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.646.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:39:44.562 [error] <0.646.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.646.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:39:44.563 [error] <0.498.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.646.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:42:15.796 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-03 16:42:15.811 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-03 16:42:15.816 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-03 16:42:15.825 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-03 16:42:15.828 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-03 16:42:15.829 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-03 16:42:15.844 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-03 16:42:15.849 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-03 16:42:15.855 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-03 16:42:15.861 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-03 16:42:15.867 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-03 16:42:15.877 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-03 16:42:15.882 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-03 16:42:15.904 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-03 16:42:15.919 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-03 16:42:15.922 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-03 16:42:15.932 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-03 16:42:15.949 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-03 16:43:13.836 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-03 16:43:13.844 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-03 16:43:13.851 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-03 16:43:13.858 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-03 16:43:13.860 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-03 16:43:13.860 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-03 16:43:13.866 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-03 16:43:13.868 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-03 16:43:13.873 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-03 16:43:13.876 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-03 16:43:13.882 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-03 16:43:13.889 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-03 16:43:13.895 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-03 16:43:13.910 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-03 16:43:13.916 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-03 16:43:13.919 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-03 16:43:13.924 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-03 16:43:13.929 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-03 16:43:14.025 [info] <0.43.0> Application railway_ui started on node nonode@nohost
2019-12-03 16:43:14.051 [info] <0.43.0> Application ex_unit started on node nonode@nohost
2019-12-03 16:43:14.465 [error] <0.552.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 gen_server <0.552.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"6cf849bc-cbdb-40b3-aead-5b0234de...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:43:14.494 [error] <0.552.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 CRASH REPORT Process <0.552.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"6cf849bc-cbdb-40b3-aead-5b0234de...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:43:14.494 [error] <0.434.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.552.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"6cf849bc-cbdb-40b3-aead-5b0234de...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10 in context child_terminated
2019-12-03 16:43:14.576 [error] <0.560.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 gen_server <0.560.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:43:14.577 [error] <0.560.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 CRASH REPORT Process <0.560.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:43:14.577 [error] <0.434.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.560.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10 in context child_terminated
2019-12-03 16:43:14.619 [error] <0.564.0> gen_server <0.564.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.published_message_search_results_count/2 in process #PID<0.564.0> (or in its callers [#PID<0.561.0>]) with args [\"correlation_id\", \"db36c23a-0c28-4833-9ad4-b907f7c5a6ba\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599
2019-12-03 16:43:14.620 [error] <0.564.0> CRASH REPORT Process <0.564.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.published_message_search_results_count/2 in process #PID<0.564.0> (or in its callers [#PID<0.561.0>]) with args [\"correlation_id\", \"db36c23a-0c28-4833-9ad4-b907f7c5a6ba\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599
2019-12-03 16:43:14.620 [error] <0.434.0> Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.564.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.published_message_search_results_count/2 in process #PID<0.564.0> (or in its callers [#PID<0.561.0>]) with args [\"correlation_id\", \"db36c23a-0c28-4833-9ad4-b907f7c5a6ba\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599 in context child_terminated
2019-12-03 16:43:14.687 [error] <0.574.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.574.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:43:14.693 [error] <0.574.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.574.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"9f56eee1-7779-4825-80c5-95dea354...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:43:14.693 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.574.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"9f56eee1-7779-4825-80c5-95dea354...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:43:14.739 [error] <0.582.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.582.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:43:14.740 [error] <0.582.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.582.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:43:14.740 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.582.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:43:14.767 [error] <0.586.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.586.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:43:14.768 [error] <0.586.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.586.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"d11448d5-daaa-43b3-85d...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:43:14.768 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.586.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"d11448d5-daaa-43b3-85d...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:45:36.723 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-03 16:45:36.736 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-03 16:45:36.743 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-03 16:45:36.751 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-03 16:45:36.754 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-03 16:45:36.754 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-03 16:45:36.763 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-03 16:45:36.767 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-03 16:45:36.772 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-03 16:45:36.779 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-03 16:45:36.786 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-03 16:45:36.793 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-03 16:45:36.798 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-03 16:45:36.810 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-03 16:45:36.817 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-03 16:45:36.822 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-03 16:45:36.829 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-03 16:45:36.851 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-03 16:45:37.013 [warning] <0.375.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-03 16:45:37.352 [error] <0.548.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 gen_server <0.548.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:45:37.373 [error] <0.548.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 CRASH REPORT Process <0.548.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10
2019-12-03 16:45:37.374 [error] <0.434.0>@Elixir.RailwayUiWeb.PublishedMessageLive.Index:handle_event:10 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.548.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Cr...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) line 10 in context child_terminated
2019-12-03 16:45:37.593 [error] <0.570.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.570.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:45:37.599 [error] <0.570.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:45:37.600 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.570.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:45:37.636 [error] <0.574.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.574.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:45:37.637 [error] <0.574.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.574.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"9dcd51fe-e8c8-4a63-b4b...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:45:37.638 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.574.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"9dcd51fe-e8c8-4a63-b4b...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:45:37.702 [error] <0.582.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.582.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:45:37.703 [error] <0.582.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.582.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"3dd26e96-5229-46fd-891d-41ed0956...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:45:37.704 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.582.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"uuid">>,<<"value">> => <<"3dd26e96-5229-46fd-891d-41ed0956...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:46:41.984 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-03 16:46:41.998 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-03 16:46:42.007 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-03 16:46:42.016 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-03 16:46:42.020 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-03 16:46:42.020 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-03 16:46:42.028 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-03 16:46:42.032 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-03 16:46:42.051 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-03 16:46:42.057 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-03 16:46:42.062 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-03 16:46:42.068 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-03 16:46:42.075 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-03 16:46:42.108 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-03 16:46:42.122 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-03 16:46:42.125 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-03 16:46:42.131 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-03 16:46:42.162 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-03 16:46:43.001 [warning] <0.375.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-03 16:46:43.001 [error] <0.570.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.570.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:46:43.025 [error] <0.570.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"2cd2890f-c2e8-4417-814...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:46:43.026 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.570.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"search">> => #{<<"query">> => <<"correlation_id">>,<<"value">> => <<"2cd2890f-c2e8-4417-814...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:46:43.141 [error] <0.582.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.582.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:46:43.142 [error] <0.582.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.582.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:46:43.143 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.582.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
2019-12-03 16:47:06.596 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-03 16:47:06.604 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-03 16:47:06.609 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-03 16:47:06.616 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-03 16:47:06.619 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-03 16:47:06.619 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-03 16:47:06.624 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-03 16:47:06.627 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-03 16:47:06.630 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-03 16:47:06.633 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-03 16:47:06.638 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-03 16:47:06.644 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-03 16:47:06.648 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-03 16:47:06.660 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-03 16:47:06.669 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-03 16:47:06.672 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-03 16:47:06.676 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-03 16:47:06.680 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-03 16:47:07.009 [warning] <0.375.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-03 16:47:07.321 [error] <0.570.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.570.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-12-03 16:47:07.336 [error] <0.570.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...})
2019-12-03 16:47:07.336 [error] <0.434.0>@Elixir.RailwayUiWeb.ConsumedMessageLive.Index:handle_event Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.570.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.ConsumedMessageLive.Index':handle_event(<<"search">>, #{<<"page">> => <<"2">>,<<"search">> => #{<<"query">> => <<"message_type">>,<<"value">> => <<"Ba...">>}}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => nil,state => #{'__struct__' => ...,...},...},...}) in context child_terminated
