2019-12-02 00:01:45.038 [error] <0.2329.0> gen_server <0.2329.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:01:45.038 [error] <0.2329.0> CRASH REPORT Process <0.2329.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:01:45.038 [error] <0.2325.0> gen_server <0.2325.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:01:45.040 [error] <0.2324.0> Supervisor {<0.2324.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.320>, <0.2325.0>, <0.2327.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60053 -> 127.0.0.1:5672">>) at <0.2329.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:01:45.040 [error] <0.2324.0> Supervisor {<0.2324.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.320>, <0.2325.0>, <0.2327.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60053 -> 127.0.0.1:5672">>) at <0.2329.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:01:45.040 [error] <0.2325.0> CRASH REPORT Process <0.2325.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:01:45.041 [error] <0.2323.0> Supervisor {<0.2323.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2324.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2325.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:01:45.042 [error] <0.2323.0> Supervisor {<0.2323.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2324.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2325.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:01:45.042 [error] <0.2320.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:01:45.042 [error] <0.2320.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:01:45.043 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2320.0> exit with reason no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 00:01:46.010 [warning] <0.387.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 00:55:51.027 [error] <0.2350.0> gen_server <0.2350.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:55:51.027 [error] <0.2350.0> CRASH REPORT Process <0.2350.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:55:51.027 [error] <0.2346.0> gen_server <0.2346.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:55:51.028 [error] <0.2345.0> Supervisor {<0.2345.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.321>, <0.2346.0>, <0.2348.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60100 -> 127.0.0.1:5672">>) at <0.2350.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:55:51.028 [error] <0.2345.0> Supervisor {<0.2345.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.321>, <0.2346.0>, <0.2348.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60100 -> 127.0.0.1:5672">>) at <0.2350.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:55:51.029 [error] <0.2346.0> CRASH REPORT Process <0.2346.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:55:51.030 [error] <0.2341.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:55:51.044 [error] <0.2341.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:55:51.044 [error] <0.2344.0> Supervisor {<0.2344.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2345.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2346.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:55:51.044 [error] <0.2344.0> Supervisor {<0.2344.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2345.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2346.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:55:51.044 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2341.0> exit with reason no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 01:49:57.042 [error] <0.2378.0> gen_server <0.2378.0> terminated with reason: {socket_error,timeout}
2019-12-02 01:49:57.042 [error] <0.2378.0> CRASH REPORT Process <0.2378.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 01:49:57.043 [error] <0.2373.0> gen_server <0.2373.0> terminated with reason: {socket_error,timeout}
2019-12-02 01:49:57.043 [error] <0.2372.0> Supervisor {<0.2372.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.322>, <0.2373.0>, <0.2376.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60142 -> 127.0.0.1:5672">>) at <0.2378.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 01:49:57.044 [error] <0.2372.0> Supervisor {<0.2372.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.322>, <0.2373.0>, <0.2376.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60142 -> 127.0.0.1:5672">>) at <0.2378.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 01:49:57.044 [error] <0.2373.0> CRASH REPORT Process <0.2373.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 01:49:57.045 [error] <0.2368.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 01:49:57.045 [error] <0.2368.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2372.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2373.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2372.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2373.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.2372.0> exit with reason shutdown in context shutdown_error
2019-12-02 01:49:57.054 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2368.0> exit with reason no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 01:49:58.005 [warning] <0.387.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 02:31:06.037 [error] <0.2400.0> gen_server <0.2400.0> terminated with reason: {socket_error,timeout}
2019-12-02 02:31:06.037 [error] <0.2400.0> CRASH REPORT Process <0.2400.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 02:31:06.037 [error] <0.2395.0> gen_server <0.2395.0> terminated with reason: {socket_error,timeout}
2019-12-02 02:31:06.040 [error] <0.2394.0> Supervisor {<0.2394.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.323>, <0.2395.0>, <0.2398.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60193 -> 127.0.0.1:5672">>) at <0.2400.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 02:31:06.041 [error] <0.2394.0> Supervisor {<0.2394.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.323>, <0.2395.0>, <0.2398.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60193 -> 127.0.0.1:5672">>) at <0.2400.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 02:31:06.041 [error] <0.2395.0> CRASH REPORT Process <0.2395.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 02:31:06.042 [error] <0.2390.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 02:31:06.059 [error] <0.2390.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 02:31:06.059 [error] <0.2393.0> Supervisor {<0.2393.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2394.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2395.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 02:31:06.059 [error] <0.2393.0> Supervisor {<0.2393.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2394.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2395.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 02:31:06.059 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2390.0> exit with reason no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 03:25:12.046 [error] <0.2422.0> gen_server <0.2422.0> terminated with reason: {socket_error,timeout}
2019-12-02 03:25:12.046 [error] <0.2422.0> CRASH REPORT Process <0.2422.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 03:25:12.047 [error] <0.2417.0> Supervisor {<0.2417.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.324>, <0.2418.0>, <0.2420.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60246 -> 127.0.0.1:5672">>) at <0.2422.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 03:25:12.047 [error] <0.2417.0> Supervisor {<0.2417.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.324>, <0.2418.0>, <0.2420.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60246 -> 127.0.0.1:5672">>) at <0.2422.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 03:25:12.047 [error] <0.2418.0> gen_server <0.2418.0> terminated with reason: {socket_error,timeout}
2019-12-02 03:25:12.047 [error] <0.2418.0> CRASH REPORT Process <0.2418.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 03:25:12.047 [error] <0.2413.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 03:25:12.048 [error] <0.2416.0> Supervisor {<0.2416.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2417.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2418.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 03:25:12.048 [error] <0.2416.0> Supervisor {<0.2416.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2417.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2418.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 03:25:12.048 [error] <0.2413.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 03:25:12.049 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2413.0> exit with reason no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 03:25:13.000 [warning] <0.387.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 04:19:18.031 [error] <0.2444.0> gen_server <0.2444.0> terminated with reason: {socket_error,timeout}
2019-12-02 04:19:18.031 [error] <0.2444.0> CRASH REPORT Process <0.2444.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 04:19:18.031 [error] <0.2440.0> gen_server <0.2440.0> terminated with reason: {socket_error,timeout}
2019-12-02 04:19:18.032 [error] <0.2439.0> Supervisor {<0.2439.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.325>, <0.2440.0>, <0.2442.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60304 -> 127.0.0.1:5672">>) at <0.2444.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 04:19:18.032 [error] <0.2439.0> Supervisor {<0.2439.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.325>, <0.2440.0>, <0.2442.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60304 -> 127.0.0.1:5672">>) at <0.2444.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 04:19:18.032 [error] <0.2440.0> CRASH REPORT Process <0.2440.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 04:19:18.034 [error] <0.2435.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 04:19:18.044 [error] <0.2435.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 04:19:18.045 [error] <0.2438.0> Supervisor {<0.2438.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2439.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2440.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 04:19:18.045 [error] <0.2438.0> Supervisor {<0.2438.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2439.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2440.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 04:19:18.045 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2435.0> exit with reason no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 05:13:24.048 [error] <0.2466.0> gen_server <0.2466.0> terminated with reason: {socket_error,timeout}
2019-12-02 05:13:24.048 [error] <0.2466.0> CRASH REPORT Process <0.2466.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 05:13:24.048 [error] <0.2461.0> gen_server <0.2461.0> terminated with reason: {socket_error,timeout}
2019-12-02 05:13:24.049 [error] <0.2460.0> Supervisor {<0.2460.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.326>, <0.2461.0>, <0.2464.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60362 -> 127.0.0.1:5672">>) at <0.2466.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 05:13:24.049 [error] <0.2460.0> Supervisor {<0.2460.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.326>, <0.2461.0>, <0.2464.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60362 -> 127.0.0.1:5672">>) at <0.2466.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 05:13:24.049 [error] <0.2461.0> CRASH REPORT Process <0.2461.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 05:13:24.049 [error] <0.2456.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 05:13:24.050 [error] <0.2456.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2460.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2461.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2460.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2461.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.2460.0> exit with reason shutdown in context shutdown_error
2019-12-02 05:13:24.051 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2456.0> exit with reason no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 05:13:25.014 [warning] <0.387.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 06:07:30.045 [error] <0.2488.0> gen_server <0.2488.0> terminated with reason: {socket_error,timeout}
2019-12-02 06:07:30.045 [error] <0.2488.0> CRASH REPORT Process <0.2488.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 06:07:30.045 [error] <0.2484.0> gen_server <0.2484.0> terminated with reason: {socket_error,timeout}
2019-12-02 06:07:30.046 [error] <0.2484.0> CRASH REPORT Process <0.2484.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 06:07:30.046 [error] <0.2483.0> Supervisor {<0.2483.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.327>, <0.2484.0>, <0.2486.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60423 -> 127.0.0.1:5672">>) at <0.2488.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 06:07:30.046 [error] <0.2483.0> Supervisor {<0.2483.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.327>, <0.2484.0>, <0.2486.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60423 -> 127.0.0.1:5672">>) at <0.2488.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 06:07:30.046 [error] <0.2482.0> Supervisor {<0.2482.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2483.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2484.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 06:07:30.046 [error] <0.2482.0> Supervisor {<0.2482.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2483.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2484.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 06:07:30.047 [error] <0.2479.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 06:07:30.048 [error] <0.2479.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 06:07:30.048 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2479.0> exit with reason no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:01:36.033 [error] <0.2510.0> gen_server <0.2510.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:01:36.033 [error] <0.2510.0> CRASH REPORT Process <0.2510.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:01:36.033 [error] <0.2505.0> gen_server <0.2505.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:01:36.034 [error] <0.2504.0> Supervisor {<0.2504.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.328>, <0.2505.0>, <0.2508.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60488 -> 127.0.0.1:5672">>) at <0.2510.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:01:36.034 [error] <0.2504.0> Supervisor {<0.2504.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.328>, <0.2505.0>, <0.2508.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60488 -> 127.0.0.1:5672">>) at <0.2510.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:01:36.034 [error] <0.2505.0> CRASH REPORT Process <0.2505.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:01:36.036 [error] <0.2500.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:01:36.045 [error] <0.2503.0> Supervisor {<0.2503.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2504.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2505.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:01:36.045 [error] <0.2503.0> Supervisor {<0.2503.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2504.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2505.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:01:36.045 [error] <0.2500.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:01:36.046 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2500.0> exit with reason no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:01:37.000 [warning] <0.387.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 07:25:58.032 [error] <0.2532.0> gen_server <0.2532.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:25:58.032 [error] <0.2532.0> CRASH REPORT Process <0.2532.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:25:58.032 [error] <0.2528.0> gen_server <0.2528.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:25:58.033 [error] <0.2528.0> CRASH REPORT Process <0.2528.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:25:58.045 [error] <0.2527.0> Supervisor {<0.2527.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.329>, <0.2528.0>, <0.2530.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60525 -> 127.0.0.1:5672">>) at <0.2532.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:25:58.045 [error] <0.2527.0> Supervisor {<0.2527.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.329>, <0.2528.0>, <0.2530.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60525 -> 127.0.0.1:5672">>) at <0.2532.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:25:58.045 [error] <0.2526.0> Supervisor {<0.2526.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2527.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2528.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:25:58.045 [error] <0.2526.0> Supervisor {<0.2526.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2527.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2528.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:25:58.047 [error] <0.2523.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:25:58.047 [error] <0.2523.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:25:58.048 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2523.0> exit with reason no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:35:08.494 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-02 07:35:08.503 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-02 07:35:08.508 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-02 07:35:08.515 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-02 07:35:08.517 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-02 07:35:08.517 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-02 07:35:08.525 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-02 07:35:08.527 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-02 07:35:08.532 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-02 07:35:08.536 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-02 07:35:08.542 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-02 07:35:08.551 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-02 07:35:08.555 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-02 07:35:08.568 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-02 07:35:08.574 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-02 07:35:08.577 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-02 07:35:08.582 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-02 07:35:08.588 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-02 07:35:09.014 [warning] <0.375.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 07:35:09.150 [error] <0.556.0> gen_server <0.556.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599
2019-12-02 07:35:09.163 [error] <0.556.0> CRASH REPORT Process <0.556.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599
2019-12-02 07:35:09.163 [error] <0.434.0> Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.556.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599 in context child_terminated
2019-12-02 07:40:54.700 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-02 07:40:54.708 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-02 07:40:54.712 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-02 07:40:54.719 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-02 07:40:54.722 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-02 07:40:54.722 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-02 07:40:54.728 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-02 07:40:54.730 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-02 07:40:54.735 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-02 07:40:54.738 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-02 07:40:54.743 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-02 07:40:54.749 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-02 07:40:54.753 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-02 07:40:54.768 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-02 07:40:54.774 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-02 07:40:54.776 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-02 07:40:54.781 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-02 07:40:54.786 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-02 07:40:55.011 [warning] <0.375.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-02 07:40:55.341 [error] <0.560.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 gen_server <0.560.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122
2019-12-02 07:40:55.356 [error] <0.560.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 CRASH REPORT Process <0.560.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122
2019-12-02 07:40:55.357 [error] <0.434.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.560.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122 in context child_terminated
