2019-12-04 00:44:01.133 [error] <0.1238.0> gen_server <0.1238.0> terminated with reason: {socket_error,timeout}
2019-12-04 00:44:01.133 [error] <0.1233.0> gen_server <0.1233.0> terminated with reason: {socket_error,timeout}
2019-12-04 00:44:01.133 [error] <0.1238.0> CRASH REPORT Process <0.1238.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 00:44:01.134 [error] <0.1232.0> Supervisor {<0.1232.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.148>, <0.1233.0>, <0.1236.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59474 -> 127.0.0.1:5672">>) at <0.1238.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 00:44:01.134 [error] <0.1232.0> Supervisor {<0.1232.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.148>, <0.1233.0>, <0.1236.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59474 -> 127.0.0.1:5672">>) at <0.1238.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 00:44:01.134 [error] <0.1233.0> CRASH REPORT Process <0.1233.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 00:44:01.134 [error] <0.1231.0> Supervisor {<0.1231.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1232.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1233.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 00:44:01.134 [error] <0.1231.0> Supervisor {<0.1231.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1232.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1233.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 00:44:01.134 [error] <0.1228.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1233.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 00:44:01.135 [error] <0.1228.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1233.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 00:44:01.136 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1228.0> exit with reason no such process or port in call to gen_server:call(<0.1233.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 01:38:13.683 [error] <0.1262.0> gen_server <0.1262.0> terminated with reason: {socket_error,timeout}
2019-12-04 01:38:13.683 [error] <0.1262.0> CRASH REPORT Process <0.1262.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 01:38:13.683 [error] <0.1256.0> gen_server <0.1256.0> terminated with reason: {socket_error,timeout}
2019-12-04 01:38:13.683 [error] <0.1255.0> Supervisor {<0.1255.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.149>, <0.1256.0>, <0.1260.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59586 -> 127.0.0.1:5672">>) at <0.1262.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 01:38:13.684 [error] <0.1255.0> Supervisor {<0.1255.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.149>, <0.1256.0>, <0.1260.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59586 -> 127.0.0.1:5672">>) at <0.1262.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 01:38:13.684 [error] <0.1256.0> CRASH REPORT Process <0.1256.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 01:38:13.684 [error] <0.1251.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1256.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 01:38:13.684 [error] <0.1254.0> Supervisor {<0.1254.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1255.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1256.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 01:38:13.684 [error] <0.1254.0> Supervisor {<0.1254.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1255.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1256.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 01:38:13.685 [error] <0.1254.0> Supervisor {<0.1254.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1255.0> exit with reason shutdown in context shutdown_error
2019-12-04 01:38:13.685 [error] <0.1251.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1256.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 01:38:13.685 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1251.0> exit with reason no such process or port in call to gen_server:call(<0.1256.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 01:38:14.008 [warning] <0.391.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 02:32:13.059 [error] <0.1287.0> gen_server <0.1287.0> terminated with reason: {socket_error,timeout}
2019-12-04 02:32:13.059 [error] <0.1287.0> CRASH REPORT Process <0.1287.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 02:32:13.059 [error] <0.1283.0> gen_server <0.1283.0> terminated with reason: {socket_error,timeout}
2019-12-04 02:32:13.059 [error] <0.1282.0> Supervisor {<0.1282.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.150>, <0.1283.0>, <0.1285.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59655 -> 127.0.0.1:5672">>) at <0.1287.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 02:32:13.059 [error] <0.1282.0> Supervisor {<0.1282.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.150>, <0.1283.0>, <0.1285.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59655 -> 127.0.0.1:5672">>) at <0.1287.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 02:32:13.059 [error] <0.1283.0> CRASH REPORT Process <0.1283.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 02:32:13.059 [error] <0.1281.0> Supervisor {<0.1281.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1282.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1283.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 02:32:13.060 [error] <0.1281.0> Supervisor {<0.1281.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1282.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1283.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 02:32:13.060 [error] <0.1278.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1283.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 02:32:13.061 [error] <0.1278.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1283.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 02:32:13.061 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1278.0> exit with reason no such process or port in call to gen_server:call(<0.1283.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 03:26:19.006 [error] <0.1309.0> gen_server <0.1309.0> terminated with reason: {socket_error,timeout}
2019-12-04 03:26:19.007 [error] <0.1309.0> CRASH REPORT Process <0.1309.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 03:26:19.007 [error] <0.1304.0> gen_server <0.1304.0> terminated with reason: {socket_error,timeout}
2019-12-04 03:26:19.028 [error] <0.1303.0> Supervisor {<0.1303.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.151>, <0.1304.0>, <0.1307.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59688 -> 127.0.0.1:5672">>) at <0.1309.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 03:26:19.028 [error] <0.1303.0> Supervisor {<0.1303.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.151>, <0.1304.0>, <0.1307.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59688 -> 127.0.0.1:5672">>) at <0.1309.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 03:26:19.029 [error] <0.1304.0> CRASH REPORT Process <0.1304.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 03:26:19.029 [error] <0.1302.0> Supervisor {<0.1302.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1303.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1304.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 03:26:19.029 [error] <0.1302.0> Supervisor {<0.1302.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1303.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1304.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 03:26:19.030 [error] <0.1299.0> gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.1304.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}},60000]}} in gen_server:call/3 line 223
2019-12-04 03:26:19.031 [error] <0.1299.0> CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.1304.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}},60000]}} in gen_server:call/3 line 223
2019-12-04 03:26:19.031 [error] <0.428.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1299.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.1304.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}},60000]}} in context child_terminated
2019-12-04 03:26:20.009 [warning] <0.391.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 04:20:25.014 [error] <0.1331.0> gen_server <0.1331.0> terminated with reason: {socket_error,timeout}
2019-12-04 04:20:25.015 [error] <0.1331.0> CRASH REPORT Process <0.1331.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 04:20:25.015 [error] <0.1327.0> gen_server <0.1327.0> terminated with reason: {socket_error,timeout}
2019-12-04 04:20:25.016 [error] <0.1326.0> Supervisor {<0.1326.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.152>, <0.1327.0>, <0.1329.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59746 -> 127.0.0.1:5672">>) at <0.1331.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 04:20:25.016 [error] <0.1326.0> Supervisor {<0.1326.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.152>, <0.1327.0>, <0.1329.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59746 -> 127.0.0.1:5672">>) at <0.1331.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 04:20:25.016 [error] <0.1327.0> CRASH REPORT Process <0.1327.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 04:20:25.033 [error] <0.1325.0> Supervisor {<0.1325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1326.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1327.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 04:20:25.033 [error] <0.1325.0> Supervisor {<0.1325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1326.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1327.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 04:20:25.033 [error] <0.1322.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1327.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 04:20:25.033 [error] <0.1325.0> Supervisor {<0.1325.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1326.0> exit with reason shutdown in context shutdown_error
2019-12-04 04:20:25.033 [error] <0.1322.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1327.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 04:20:25.034 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1322.0> exit with reason no such process or port in call to gen_server:call(<0.1327.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 05:14:31.015 [error] <0.1353.0> gen_server <0.1353.0> terminated with reason: {socket_error,timeout}
2019-12-04 05:14:31.015 [error] <0.1353.0> CRASH REPORT Process <0.1353.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 05:14:31.015 [error] <0.1348.0> gen_server <0.1348.0> terminated with reason: {socket_error,timeout}
2019-12-04 05:14:31.016 [error] <0.1347.0> Supervisor {<0.1347.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.153>, <0.1348.0>, <0.1351.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59792 -> 127.0.0.1:5672">>) at <0.1353.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 05:14:31.017 [error] <0.1347.0> Supervisor {<0.1347.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.153>, <0.1348.0>, <0.1351.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59792 -> 127.0.0.1:5672">>) at <0.1353.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 05:14:31.017 [error] <0.1348.0> CRASH REPORT Process <0.1348.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 05:14:31.031 [error] <0.1346.0> Supervisor {<0.1346.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1347.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1348.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 05:14:31.031 [error] <0.1346.0> Supervisor {<0.1346.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1347.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1348.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 05:14:31.031 [error] <0.1343.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1348.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 05:14:31.031 [error] <0.1343.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1348.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 05:14:31.032 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1343.0> exit with reason no such process or port in call to gen_server:call(<0.1348.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 05:14:32.036 [warning] <0.391.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 06:08:37.085 [error] <0.1370.0> gen_server <0.1370.0> terminated with reason: {socket_error,timeout}
2019-12-04 06:08:37.085 [error] <0.1375.0> gen_server <0.1375.0> terminated with reason: {socket_error,timeout}
2019-12-04 06:08:37.085 [error] <0.1375.0> CRASH REPORT Process <0.1375.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 06:08:37.086 [error] <0.1370.0> CRASH REPORT Process <0.1370.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 06:08:37.086 [error] <0.1369.0> Supervisor {<0.1369.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.154>, <0.1370.0>, <0.1373.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59854 -> 127.0.0.1:5672">>) at <0.1375.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 06:08:37.086 [error] <0.1369.0> Supervisor {<0.1369.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.154>, <0.1370.0>, <0.1373.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59854 -> 127.0.0.1:5672">>) at <0.1375.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 06:08:37.086 [error] <0.1368.0> Supervisor {<0.1368.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1369.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1370.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 06:08:37.086 [error] <0.1368.0> Supervisor {<0.1368.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1369.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1370.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 06:08:37.086 [error] <0.1365.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1370.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 06:08:37.087 [error] <0.1365.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1370.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 06:08:37.087 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1365.0> exit with reason no such process or port in call to gen_server:call(<0.1370.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 07:02:43.026 [error] <0.1397.0> gen_server <0.1397.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:02:43.026 [error] <0.1397.0> CRASH REPORT Process <0.1397.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:02:43.026 [error] <0.1393.0> gen_server <0.1393.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:02:43.027 [error] <0.1392.0> Supervisor {<0.1392.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.155>, <0.1393.0>, <0.1395.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59920 -> 127.0.0.1:5672">>) at <0.1397.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:02:43.027 [error] <0.1392.0> Supervisor {<0.1392.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.155>, <0.1393.0>, <0.1395.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59920 -> 127.0.0.1:5672">>) at <0.1397.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:02:43.027 [error] <0.1393.0> CRASH REPORT Process <0.1393.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:02:43.028 [error] <0.1391.0> Supervisor {<0.1391.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1392.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1393.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:02:43.028 [error] <0.1391.0> Supervisor {<0.1391.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1392.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1393.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:02:43.029 [error] <0.1388.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1393.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:02:43.029 [error] <0.1388.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1393.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:02:43.029 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1388.0> exit with reason no such process or port in call to gen_server:call(<0.1393.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 07:02:44.020 [warning] <0.391.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 07:25:29.026 [error] <0.1419.0> gen_server <0.1419.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:25:29.026 [error] <0.1419.0> CRASH REPORT Process <0.1419.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:25:29.026 [error] <0.1414.0> Supervisor {<0.1414.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.156>, <0.1415.0>, <0.1417.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59970 -> 127.0.0.1:5672">>) at <0.1419.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:25:29.027 [error] <0.1414.0> Supervisor {<0.1414.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.156>, <0.1415.0>, <0.1417.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59970 -> 127.0.0.1:5672">>) at <0.1419.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:25:29.027 [error] <0.1415.0> gen_server <0.1415.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:25:29.028 [error] <0.1415.0> CRASH REPORT Process <0.1415.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:25:29.028 [error] <0.1410.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1415.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:25:29.029 [error] <0.1410.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1415.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:25:29.036 [error] <0.1413.0> Supervisor {<0.1413.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1414.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1415.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:25:29.036 [error] <0.1413.0> Supervisor {<0.1413.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1414.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1415.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:25:29.036 [error] <0.1413.0> Supervisor {<0.1413.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1414.0> exit with reason shutdown in context shutdown_error
2019-12-04 07:25:29.037 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1410.0> exit with reason no such process or port in call to gen_server:call(<0.1415.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 07:34:46.034 [error] <0.1441.0> gen_server <0.1441.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:34:46.034 [error] <0.1441.0> CRASH REPORT Process <0.1441.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:34:46.034 [error] <0.1437.0> gen_server <0.1437.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:34:46.035 [error] <0.1436.0> Supervisor {<0.1436.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.157>, <0.1437.0>, <0.1439.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60029 -> 127.0.0.1:5672">>) at <0.1441.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:34:46.036 [error] <0.1436.0> Supervisor {<0.1436.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.157>, <0.1437.0>, <0.1439.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60029 -> 127.0.0.1:5672">>) at <0.1441.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:34:46.036 [error] <0.1437.0> CRASH REPORT Process <0.1437.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:34:46.037 [error] <0.1432.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1437.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:34:46.038 [error] <0.1432.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1437.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:34:46.040 [error] <0.1435.0> Supervisor {<0.1435.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1436.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1437.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:34:46.040 [error] <0.1435.0> Supervisor {<0.1435.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1436.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1437.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:34:46.040 [error] <0.1435.0> Supervisor {<0.1435.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1436.0> exit with reason shutdown in context shutdown_error
2019-12-04 07:34:46.040 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1432.0> exit with reason no such process or port in call to gen_server:call(<0.1437.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 07:34:47.068 [warning] <0.391.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 07:44:02.135 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-04 07:44:02.161 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-04 07:44:02.166 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-04 07:44:02.175 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-04 07:44:02.178 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-04 07:44:02.178 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-04 07:44:02.203 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-04 07:44:02.208 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-04 07:44:02.214 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-04 07:44:02.218 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-04 07:44:02.227 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-04 07:44:02.238 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-04 07:44:02.242 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-04 07:44:02.265 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-04 07:44:02.288 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-04 07:44:02.295 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-04 07:44:02.316 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-12-04 07:44:02.361 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-12-04 07:44:02.385 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-04 07:44:02.398 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-04 07:44:02.999 [warning] <0.363.0> lager_error_logger_h dropped 142 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 07:48:32.023 [error] <0.460.0> gen_server <0.460.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:48:32.023 [error] <0.424.0> gen_server <0.424.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:48:32.172 [error] <0.424.0> CRASH REPORT Process <0.424.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:48:32.173 [error] <0.410.0> Supervisor {<0.410.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.415.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.424.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:48:32.173 [error] <0.410.0> Supervisor {<0.410.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.415.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.424.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:48:32.173 [error] <0.401.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:48:32.251 [error] <0.401.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:48:32.251 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.401.0> exit with reason no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 08:07:42.033 [error] <0.636.0> gen_server <0.636.0> terminated with reason: {socket_error,timeout}
2019-12-04 08:07:42.033 [error] <0.636.0> CRASH REPORT Process <0.636.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 08:07:42.033 [error] <0.632.0> gen_server <0.632.0> terminated with reason: {socket_error,timeout}
2019-12-04 08:07:42.033 [error] <0.632.0> CRASH REPORT Process <0.632.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 08:07:42.033 [error] <0.627.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.632.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 08:07:42.033 [error] <0.627.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.632.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 08:07:42.033 [error] <0.631.0> Supervisor {<0.631.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.97>, <0.632.0>, <0.634.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60435 -> 127.0.0.1:5672">>) at <0.636.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 08:07:42.033 [error] <0.631.0> Supervisor {<0.631.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.97>, <0.632.0>, <0.634.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60435 -> 127.0.0.1:5672">>) at <0.636.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 08:07:42.034 [error] <0.630.0> Supervisor {<0.630.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.631.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.632.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 08:07:42.034 [error] <0.630.0> Supervisor {<0.630.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.631.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.632.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 08:07:42.034 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.627.0> exit with reason no such process or port in call to gen_server:call(<0.632.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 08:07:43.003 [warning] <0.363.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 09:18:19.027 [error] <0.670.0> gen_server <0.670.0> terminated with reason: {socket_error,timeout}
2019-12-04 09:18:19.027 [error] <0.670.0> CRASH REPORT Process <0.670.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 09:18:19.028 [error] <0.666.0> gen_server <0.666.0> terminated with reason: {socket_error,timeout}
2019-12-04 09:18:19.029 [error] <0.665.0> Supervisor {<0.665.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.100>, <0.666.0>, <0.668.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60576 -> 127.0.0.1:5672">>) at <0.670.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 09:18:19.029 [error] <0.665.0> Supervisor {<0.665.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.100>, <0.666.0>, <0.668.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60576 -> 127.0.0.1:5672">>) at <0.670.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 09:18:19.029 [error] <0.666.0> CRASH REPORT Process <0.666.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 09:18:19.030 [error] <0.664.0> Supervisor {<0.664.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.665.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.666.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 09:18:19.031 [error] <0.664.0> Supervisor {<0.664.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.665.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.666.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 09:18:19.031 [error] <0.661.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.666.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 09:18:19.031 [error] <0.661.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.666.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 09:18:19.032 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.661.0> exit with reason no such process or port in call to gen_server:call(<0.666.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 10:34:01.070 [error] <0.852.0> gen_server <0.852.0> terminated with reason: {socket_error,timeout}
2019-12-04 10:34:01.070 [error] <0.847.0> gen_server <0.847.0> terminated with reason: {socket_error,timeout}
2019-12-04 10:34:01.070 [error] <0.847.0> CRASH REPORT Process <0.847.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 10:34:01.082 [error] <0.852.0> CRASH REPORT Process <0.852.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 10:34:01.082 [error] <0.846.0> Supervisor {<0.846.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.123>, <0.847.0>, <0.850.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61149 -> 127.0.0.1:5672">>) at <0.852.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 10:34:01.083 [error] <0.846.0> Supervisor {<0.846.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.123>, <0.847.0>, <0.850.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61149 -> 127.0.0.1:5672">>) at <0.852.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 10:34:01.083 [error] <0.845.0> Supervisor {<0.845.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.846.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.847.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 10:34:01.083 [error] <0.845.0> Supervisor {<0.845.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.846.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.847.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 10:34:01.089 [error] <0.842.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.847.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 10:34:01.103 [error] <0.842.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.847.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 10:34:01.104 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.842.0> exit with reason no such process or port in call to gen_server:call(<0.847.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 10:34:02.008 [warning] <0.363.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 11:33:59.052 [error] <0.903.0> gen_server <0.903.0> terminated with reason: {socket_error,timeout}
2019-12-04 11:33:59.053 [error] <0.903.0> CRASH REPORT Process <0.903.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 11:33:59.053 [error] <0.899.0> gen_server <0.899.0> terminated with reason: {socket_error,timeout}
2019-12-04 11:33:59.053 [error] <0.899.0> CRASH REPORT Process <0.899.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 11:33:59.054 [error] <0.894.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.899.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 11:33:59.055 [error] <0.894.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.899.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 11:33:59.055 [error] <0.896.0> Supervisor {<0.896.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.898.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.899.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 11:33:59.055 [error] <0.896.0> Supervisor {<0.896.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.898.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.899.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 11:33:59.056 [error] <0.898.0> Supervisor {<0.898.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.126>, <0.899.0>, <0.901.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61573 -> 127.0.0.1:5672">>) at <0.903.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 11:33:59.056 [error] <0.898.0> Supervisor {<0.898.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.126>, <0.899.0>, <0.901.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61573 -> 127.0.0.1:5672">>) at <0.903.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 11:33:59.056 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.894.0> exit with reason no such process or port in call to gen_server:call(<0.899.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 11:37:08.567 [info] <0.43.0> Application lager started on node nonode@nohost
2019-12-04 11:37:08.777 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-12-04 11:37:08.785 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-12-04 11:37:08.805 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-12-04 11:37:08.817 [info] <0.43.0> Application recon started on node nonode@nohost
2019-12-04 11:37:08.817 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-12-04 11:37:08.863 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-12-04 11:37:08.885 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-12-04 11:37:09.195 [info] <0.43.0> Application elixir_uuid started on node nonode@nohost
2019-12-04 11:37:09.217 [info] <0.43.0> Application protobuf started on node nonode@nohost
2019-12-04 11:37:09.222 [info] <0.43.0> Application google_protos started on node nonode@nohost
2019-12-04 11:37:09.233 [info] <0.43.0> Application railway_ipc started on node nonode@nohost
2019-12-04 11:37:09.239 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2019-12-04 11:37:09.277 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-12-04 11:37:09.290 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-12-04 11:37:09.295 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-12-04 11:37:09.313 [info] <0.43.0> Application file_system started on node nonode@nohost
2019-12-04 11:37:09.356 [info] <0.43.0> Application phoenix_live_reload started on node nonode@nohost
2019-12-04 11:37:09.393 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2019-12-04 11:37:09.419 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2019-12-04 11:37:10.227 [warning] <0.381.0> lager_error_logger_h dropped 142 messages in the last second that exceeded the limit of 50 messages/sec
2019-12-04 11:37:19.369 [error] <0.626.0> CRASH REPORT Process <0.626.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => view,message => nil,term => #{}},[{'Elixir.RailwayUiWeb.MessageLive.SearchComponent',mount,1,[{file,"lib/railway_ui_web/live/message_live/search_component.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,170}]},{'Elixir.Phoenix.LiveView.Diff',ensure_component,3,[{file,"lib/phoenix_live_view/diff.ex"},{line,332}]},{'Elixir.Phoenix.LiveView.Diff',traverse_component,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 11:37:19.458 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.624.0>,1,<0.626.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => view,message => nil,term => #{}},[{'Elixir.RailwayUiWeb.MessageLive.SearchComponent',mount,1,[{file,"lib/railway_ui_web/live/message_live/search_component.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,170}]},{'Elixir.Phoenix.LiveView.Diff',ensure_component,3,[{file,"lib..."},...]},...]},...},...]},...}}
2019-12-04 11:37:26.985 [error] <0.636.0> CRASH REPORT Process <0.636.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => view,message => nil,term => #{}},[{'Elixir.RailwayUiWeb.MessageLive.SearchComponent',mount,1,[{file,"lib/railway_ui_web/live/message_live/search_component.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,170}]},{'Elixir.Phoenix.LiveView.Diff',ensure_component,3,[{file,"lib/phoenix_live_view/diff.ex"},{line,332}]},{'Elixir.Phoenix.LiveView.Diff',traverse_component,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 11:37:26.993 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.634.0>,1,<0.636.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => view,message => nil,term => #{}},[{'Elixir.RailwayUiWeb.MessageLive.SearchComponent',mount,1,[{file,"lib/railway_ui_web/live/message_live/search_component.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,170}]},{'Elixir.Phoenix.LiveView.Diff',ensure_component,3,[{file,"lib..."},...]},...]},...},...]},...}}
