2019-12-04 00:44:01.133 [error] <0.1238.0> gen_server <0.1238.0> terminated with reason: {socket_error,timeout}
2019-12-04 00:44:01.133 [error] <0.1233.0> gen_server <0.1233.0> terminated with reason: {socket_error,timeout}
2019-12-04 00:44:01.133 [error] <0.1238.0> CRASH REPORT Process <0.1238.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 00:44:01.134 [error] <0.1232.0> Supervisor {<0.1232.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.148>, <0.1233.0>, <0.1236.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59474 -> 127.0.0.1:5672">>) at <0.1238.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 00:44:01.134 [error] <0.1232.0> Supervisor {<0.1232.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.148>, <0.1233.0>, <0.1236.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59474 -> 127.0.0.1:5672">>) at <0.1238.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 00:44:01.134 [error] <0.1233.0> CRASH REPORT Process <0.1233.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 00:44:01.134 [error] <0.1231.0> Supervisor {<0.1231.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1232.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1233.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 00:44:01.134 [error] <0.1231.0> Supervisor {<0.1231.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1232.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1233.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 00:44:01.134 [error] <0.1228.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1233.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 00:44:01.135 [error] <0.1228.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1233.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 00:44:01.136 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1228.0> exit with reason no such process or port in call to gen_server:call(<0.1233.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 01:38:13.683 [error] <0.1262.0> gen_server <0.1262.0> terminated with reason: {socket_error,timeout}
2019-12-04 01:38:13.683 [error] <0.1262.0> CRASH REPORT Process <0.1262.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 01:38:13.683 [error] <0.1256.0> gen_server <0.1256.0> terminated with reason: {socket_error,timeout}
2019-12-04 01:38:13.683 [error] <0.1255.0> Supervisor {<0.1255.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.149>, <0.1256.0>, <0.1260.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59586 -> 127.0.0.1:5672">>) at <0.1262.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 01:38:13.684 [error] <0.1255.0> Supervisor {<0.1255.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.149>, <0.1256.0>, <0.1260.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59586 -> 127.0.0.1:5672">>) at <0.1262.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 01:38:13.684 [error] <0.1256.0> CRASH REPORT Process <0.1256.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 01:38:13.684 [error] <0.1251.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1256.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 01:38:13.684 [error] <0.1254.0> Supervisor {<0.1254.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1255.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1256.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 01:38:13.684 [error] <0.1254.0> Supervisor {<0.1254.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1255.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1256.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 01:38:13.685 [error] <0.1254.0> Supervisor {<0.1254.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1255.0> exit with reason shutdown in context shutdown_error
2019-12-04 01:38:13.685 [error] <0.1251.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1256.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 01:38:13.685 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1251.0> exit with reason no such process or port in call to gen_server:call(<0.1256.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 02:32:13.059 [error] <0.1287.0> gen_server <0.1287.0> terminated with reason: {socket_error,timeout}
2019-12-04 02:32:13.059 [error] <0.1287.0> CRASH REPORT Process <0.1287.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 02:32:13.059 [error] <0.1283.0> gen_server <0.1283.0> terminated with reason: {socket_error,timeout}
2019-12-04 02:32:13.059 [error] <0.1282.0> Supervisor {<0.1282.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.150>, <0.1283.0>, <0.1285.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59655 -> 127.0.0.1:5672">>) at <0.1287.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 02:32:13.059 [error] <0.1282.0> Supervisor {<0.1282.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.150>, <0.1283.0>, <0.1285.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59655 -> 127.0.0.1:5672">>) at <0.1287.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 02:32:13.059 [error] <0.1283.0> CRASH REPORT Process <0.1283.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 02:32:13.059 [error] <0.1281.0> Supervisor {<0.1281.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1282.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1283.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 02:32:13.060 [error] <0.1281.0> Supervisor {<0.1281.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1282.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1283.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 02:32:13.060 [error] <0.1278.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1283.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 02:32:13.061 [error] <0.1278.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1283.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 02:32:13.061 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1278.0> exit with reason no such process or port in call to gen_server:call(<0.1283.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 03:26:19.006 [error] <0.1309.0> gen_server <0.1309.0> terminated with reason: {socket_error,timeout}
2019-12-04 03:26:19.007 [error] <0.1309.0> CRASH REPORT Process <0.1309.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 03:26:19.007 [error] <0.1304.0> gen_server <0.1304.0> terminated with reason: {socket_error,timeout}
2019-12-04 03:26:19.028 [error] <0.1303.0> Supervisor {<0.1303.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.151>, <0.1304.0>, <0.1307.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59688 -> 127.0.0.1:5672">>) at <0.1309.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 03:26:19.028 [error] <0.1303.0> Supervisor {<0.1303.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.151>, <0.1304.0>, <0.1307.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59688 -> 127.0.0.1:5672">>) at <0.1309.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 03:26:19.029 [error] <0.1304.0> CRASH REPORT Process <0.1304.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 03:26:19.029 [error] <0.1302.0> Supervisor {<0.1302.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1303.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1304.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 03:26:19.029 [error] <0.1302.0> Supervisor {<0.1302.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1303.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1304.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 03:26:19.030 [error] <0.1299.0> gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.1304.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}},60000]}} in gen_server:call/3 line 223
2019-12-04 03:26:19.031 [error] <0.1299.0> CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.1304.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}},60000]}} in gen_server:call/3 line 223
2019-12-04 03:26:19.031 [error] <0.428.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1299.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.1304.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}},60000]}} in context child_terminated
2019-12-04 04:20:25.014 [error] <0.1331.0> gen_server <0.1331.0> terminated with reason: {socket_error,timeout}
2019-12-04 04:20:25.015 [error] <0.1331.0> CRASH REPORT Process <0.1331.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 04:20:25.015 [error] <0.1327.0> gen_server <0.1327.0> terminated with reason: {socket_error,timeout}
2019-12-04 04:20:25.016 [error] <0.1326.0> Supervisor {<0.1326.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.152>, <0.1327.0>, <0.1329.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59746 -> 127.0.0.1:5672">>) at <0.1331.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 04:20:25.016 [error] <0.1326.0> Supervisor {<0.1326.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.152>, <0.1327.0>, <0.1329.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59746 -> 127.0.0.1:5672">>) at <0.1331.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 04:20:25.016 [error] <0.1327.0> CRASH REPORT Process <0.1327.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 04:20:25.033 [error] <0.1325.0> Supervisor {<0.1325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1326.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1327.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 04:20:25.033 [error] <0.1325.0> Supervisor {<0.1325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1326.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1327.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 04:20:25.033 [error] <0.1322.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1327.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 04:20:25.033 [error] <0.1325.0> Supervisor {<0.1325.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1326.0> exit with reason shutdown in context shutdown_error
2019-12-04 04:20:25.033 [error] <0.1322.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1327.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 04:20:25.034 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1322.0> exit with reason no such process or port in call to gen_server:call(<0.1327.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 05:14:31.015 [error] <0.1353.0> gen_server <0.1353.0> terminated with reason: {socket_error,timeout}
2019-12-04 05:14:31.015 [error] <0.1353.0> CRASH REPORT Process <0.1353.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 05:14:31.015 [error] <0.1348.0> gen_server <0.1348.0> terminated with reason: {socket_error,timeout}
2019-12-04 05:14:31.016 [error] <0.1347.0> Supervisor {<0.1347.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.153>, <0.1348.0>, <0.1351.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59792 -> 127.0.0.1:5672">>) at <0.1353.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 05:14:31.017 [error] <0.1347.0> Supervisor {<0.1347.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.153>, <0.1348.0>, <0.1351.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59792 -> 127.0.0.1:5672">>) at <0.1353.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 05:14:31.017 [error] <0.1348.0> CRASH REPORT Process <0.1348.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 05:14:31.031 [error] <0.1346.0> Supervisor {<0.1346.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1347.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1348.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 05:14:31.031 [error] <0.1346.0> Supervisor {<0.1346.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1347.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1348.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 05:14:31.031 [error] <0.1343.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1348.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 05:14:31.031 [error] <0.1343.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1348.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 05:14:31.032 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1343.0> exit with reason no such process or port in call to gen_server:call(<0.1348.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 06:08:37.085 [error] <0.1370.0> gen_server <0.1370.0> terminated with reason: {socket_error,timeout}
2019-12-04 06:08:37.085 [error] <0.1375.0> gen_server <0.1375.0> terminated with reason: {socket_error,timeout}
2019-12-04 06:08:37.085 [error] <0.1375.0> CRASH REPORT Process <0.1375.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 06:08:37.086 [error] <0.1370.0> CRASH REPORT Process <0.1370.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 06:08:37.086 [error] <0.1369.0> Supervisor {<0.1369.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.154>, <0.1370.0>, <0.1373.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59854 -> 127.0.0.1:5672">>) at <0.1375.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 06:08:37.086 [error] <0.1369.0> Supervisor {<0.1369.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.154>, <0.1370.0>, <0.1373.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59854 -> 127.0.0.1:5672">>) at <0.1375.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 06:08:37.086 [error] <0.1368.0> Supervisor {<0.1368.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1369.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1370.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 06:08:37.086 [error] <0.1368.0> Supervisor {<0.1368.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1369.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1370.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 06:08:37.086 [error] <0.1365.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1370.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 06:08:37.087 [error] <0.1365.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1370.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 06:08:37.087 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1365.0> exit with reason no such process or port in call to gen_server:call(<0.1370.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 07:02:43.026 [error] <0.1397.0> gen_server <0.1397.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:02:43.026 [error] <0.1397.0> CRASH REPORT Process <0.1397.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:02:43.026 [error] <0.1393.0> gen_server <0.1393.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:02:43.027 [error] <0.1392.0> Supervisor {<0.1392.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.155>, <0.1393.0>, <0.1395.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59920 -> 127.0.0.1:5672">>) at <0.1397.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:02:43.027 [error] <0.1392.0> Supervisor {<0.1392.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.155>, <0.1393.0>, <0.1395.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59920 -> 127.0.0.1:5672">>) at <0.1397.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:02:43.027 [error] <0.1393.0> CRASH REPORT Process <0.1393.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:02:43.028 [error] <0.1391.0> Supervisor {<0.1391.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1392.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1393.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:02:43.028 [error] <0.1391.0> Supervisor {<0.1391.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1392.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1393.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:02:43.029 [error] <0.1388.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1393.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:02:43.029 [error] <0.1388.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1393.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:02:43.029 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1388.0> exit with reason no such process or port in call to gen_server:call(<0.1393.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 07:25:29.026 [error] <0.1419.0> gen_server <0.1419.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:25:29.026 [error] <0.1419.0> CRASH REPORT Process <0.1419.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:25:29.026 [error] <0.1414.0> Supervisor {<0.1414.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.156>, <0.1415.0>, <0.1417.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59970 -> 127.0.0.1:5672">>) at <0.1419.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:25:29.027 [error] <0.1414.0> Supervisor {<0.1414.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.156>, <0.1415.0>, <0.1417.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59970 -> 127.0.0.1:5672">>) at <0.1419.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:25:29.027 [error] <0.1415.0> gen_server <0.1415.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:25:29.028 [error] <0.1415.0> CRASH REPORT Process <0.1415.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:25:29.028 [error] <0.1410.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1415.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:25:29.029 [error] <0.1410.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1415.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:25:29.036 [error] <0.1413.0> Supervisor {<0.1413.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1414.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1415.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:25:29.036 [error] <0.1413.0> Supervisor {<0.1413.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1414.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1415.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:25:29.036 [error] <0.1413.0> Supervisor {<0.1413.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1414.0> exit with reason shutdown in context shutdown_error
2019-12-04 07:25:29.037 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1410.0> exit with reason no such process or port in call to gen_server:call(<0.1415.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 07:34:46.034 [error] <0.1441.0> gen_server <0.1441.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:34:46.034 [error] <0.1441.0> CRASH REPORT Process <0.1441.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:34:46.034 [error] <0.1437.0> gen_server <0.1437.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:34:46.035 [error] <0.1436.0> Supervisor {<0.1436.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.157>, <0.1437.0>, <0.1439.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60029 -> 127.0.0.1:5672">>) at <0.1441.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:34:46.036 [error] <0.1436.0> Supervisor {<0.1436.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.157>, <0.1437.0>, <0.1439.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60029 -> 127.0.0.1:5672">>) at <0.1441.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:34:46.036 [error] <0.1437.0> CRASH REPORT Process <0.1437.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:34:46.037 [error] <0.1432.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.1437.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:34:46.038 [error] <0.1432.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.1437.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:34:46.040 [error] <0.1435.0> Supervisor {<0.1435.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1436.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1437.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:34:46.040 [error] <0.1435.0> Supervisor {<0.1435.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1436.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.1437.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:34:46.040 [error] <0.1435.0> Supervisor {<0.1435.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.1436.0> exit with reason shutdown in context shutdown_error
2019-12-04 07:34:46.040 [error] <0.428.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.1432.0> exit with reason no such process or port in call to gen_server:call(<0.1437.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 07:48:32.023 [error] <0.460.0> gen_server <0.460.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:48:32.023 [error] <0.424.0> gen_server <0.424.0> terminated with reason: {socket_error,timeout}
2019-12-04 07:48:32.172 [error] <0.424.0> CRASH REPORT Process <0.424.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 07:48:32.173 [error] <0.410.0> Supervisor {<0.410.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.415.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.424.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 07:48:32.173 [error] <0.410.0> Supervisor {<0.410.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.415.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.424.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 07:48:32.173 [error] <0.401.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:48:32.251 [error] <0.401.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 07:48:32.251 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.401.0> exit with reason no such process or port in call to gen_server:call(<0.424.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 08:07:42.033 [error] <0.636.0> gen_server <0.636.0> terminated with reason: {socket_error,timeout}
2019-12-04 08:07:42.033 [error] <0.636.0> CRASH REPORT Process <0.636.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 08:07:42.033 [error] <0.632.0> gen_server <0.632.0> terminated with reason: {socket_error,timeout}
2019-12-04 08:07:42.033 [error] <0.632.0> CRASH REPORT Process <0.632.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 08:07:42.033 [error] <0.627.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.632.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 08:07:42.033 [error] <0.627.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.632.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 08:07:42.033 [error] <0.631.0> Supervisor {<0.631.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.97>, <0.632.0>, <0.634.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60435 -> 127.0.0.1:5672">>) at <0.636.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 08:07:42.033 [error] <0.631.0> Supervisor {<0.631.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.97>, <0.632.0>, <0.634.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60435 -> 127.0.0.1:5672">>) at <0.636.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 08:07:42.034 [error] <0.630.0> Supervisor {<0.630.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.631.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.632.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 08:07:42.034 [error] <0.630.0> Supervisor {<0.630.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.631.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.632.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 08:07:42.034 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.627.0> exit with reason no such process or port in call to gen_server:call(<0.632.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 09:18:19.027 [error] <0.670.0> gen_server <0.670.0> terminated with reason: {socket_error,timeout}
2019-12-04 09:18:19.027 [error] <0.670.0> CRASH REPORT Process <0.670.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 09:18:19.028 [error] <0.666.0> gen_server <0.666.0> terminated with reason: {socket_error,timeout}
2019-12-04 09:18:19.029 [error] <0.665.0> Supervisor {<0.665.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.100>, <0.666.0>, <0.668.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60576 -> 127.0.0.1:5672">>) at <0.670.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 09:18:19.029 [error] <0.665.0> Supervisor {<0.665.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.100>, <0.666.0>, <0.668.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60576 -> 127.0.0.1:5672">>) at <0.670.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 09:18:19.029 [error] <0.666.0> CRASH REPORT Process <0.666.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 09:18:19.030 [error] <0.664.0> Supervisor {<0.664.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.665.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.666.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 09:18:19.031 [error] <0.664.0> Supervisor {<0.664.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.665.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.666.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 09:18:19.031 [error] <0.661.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.666.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 09:18:19.031 [error] <0.661.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.666.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 09:18:19.032 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.661.0> exit with reason no such process or port in call to gen_server:call(<0.666.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 10:34:01.070 [error] <0.852.0> gen_server <0.852.0> terminated with reason: {socket_error,timeout}
2019-12-04 10:34:01.070 [error] <0.847.0> gen_server <0.847.0> terminated with reason: {socket_error,timeout}
2019-12-04 10:34:01.070 [error] <0.847.0> CRASH REPORT Process <0.847.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 10:34:01.082 [error] <0.852.0> CRASH REPORT Process <0.852.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 10:34:01.082 [error] <0.846.0> Supervisor {<0.846.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.123>, <0.847.0>, <0.850.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61149 -> 127.0.0.1:5672">>) at <0.852.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 10:34:01.083 [error] <0.846.0> Supervisor {<0.846.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.123>, <0.847.0>, <0.850.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61149 -> 127.0.0.1:5672">>) at <0.852.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 10:34:01.083 [error] <0.845.0> Supervisor {<0.845.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.846.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.847.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 10:34:01.083 [error] <0.845.0> Supervisor {<0.845.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.846.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.847.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 10:34:01.089 [error] <0.842.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.847.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 10:34:01.103 [error] <0.842.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.847.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 10:34:01.104 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.842.0> exit with reason no such process or port in call to gen_server:call(<0.847.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 11:33:59.052 [error] <0.903.0> gen_server <0.903.0> terminated with reason: {socket_error,timeout}
2019-12-04 11:33:59.053 [error] <0.903.0> CRASH REPORT Process <0.903.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 11:33:59.053 [error] <0.899.0> gen_server <0.899.0> terminated with reason: {socket_error,timeout}
2019-12-04 11:33:59.053 [error] <0.899.0> CRASH REPORT Process <0.899.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 11:33:59.054 [error] <0.894.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.899.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 11:33:59.055 [error] <0.894.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.899.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 11:33:59.055 [error] <0.896.0> Supervisor {<0.896.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.898.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.899.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 11:33:59.055 [error] <0.896.0> Supervisor {<0.896.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.898.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.899.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 11:33:59.056 [error] <0.898.0> Supervisor {<0.898.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.126>, <0.899.0>, <0.901.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61573 -> 127.0.0.1:5672">>) at <0.903.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 11:33:59.056 [error] <0.898.0> Supervisor {<0.898.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.126>, <0.899.0>, <0.901.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61573 -> 127.0.0.1:5672">>) at <0.903.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 11:33:59.056 [error] <0.400.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.894.0> exit with reason no such process or port in call to gen_server:call(<0.899.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 11:37:19.369 [error] <0.626.0> CRASH REPORT Process <0.626.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => view,message => nil,term => #{}},[{'Elixir.RailwayUiWeb.MessageLive.SearchComponent',mount,1,[{file,"lib/railway_ui_web/live/message_live/search_component.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,170}]},{'Elixir.Phoenix.LiveView.Diff',ensure_component,3,[{file,"lib/phoenix_live_view/diff.ex"},{line,332}]},{'Elixir.Phoenix.LiveView.Diff',traverse_component,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 11:37:19.458 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.624.0>,1,<0.626.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => view,message => nil,term => #{}},[{'Elixir.RailwayUiWeb.MessageLive.SearchComponent',mount,1,[{file,"lib/railway_ui_web/live/message_live/search_component.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,170}]},{'Elixir.Phoenix.LiveView.Diff',ensure_component,3,[{file,"lib..."},...]},...]},...},...]},...}}
2019-12-04 11:37:26.985 [error] <0.636.0> CRASH REPORT Process <0.636.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => view,message => nil,term => #{}},[{'Elixir.RailwayUiWeb.MessageLive.SearchComponent',mount,1,[{file,"lib/railway_ui_web/live/message_live/search_component.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,170}]},{'Elixir.Phoenix.LiveView.Diff',ensure_component,3,[{file,"lib/phoenix_live_view/diff.ex"},{line,332}]},{'Elixir.Phoenix.LiveView.Diff',traverse_component,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 11:37:26.993 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.634.0>,1,<0.636.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => view,message => nil,term => #{}},[{'Elixir.RailwayUiWeb.MessageLive.SearchComponent',mount,1,[{file,"lib/railway_ui_web/live/message_live/search_component.ex"},{line,10}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,170}]},{'Elixir.Phoenix.LiveView.Diff',ensure_component,3,[{file,"lib..."},...]},...]},...},...]},...}}
2019-12-04 12:14:41.027 [error] <0.477.0> gen_server <0.477.0> terminated with reason: {socket_error,timeout}
2019-12-04 12:14:41.027 [error] <0.441.0> gen_server <0.441.0> terminated with reason: {socket_error,timeout}
2019-12-04 12:14:41.156 [error] <0.441.0> CRASH REPORT Process <0.441.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 12:14:41.156 [error] <0.428.0> Supervisor {<0.428.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.433.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.441.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 12:14:41.156 [error] <0.428.0> Supervisor {<0.428.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.433.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.441.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 12:14:41.157 [error] <0.419.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.441.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 12:14:41.202 [error] <0.419.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.441.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 12:14:41.203 [error] <0.418.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.419.0> exit with reason no such process or port in call to gen_server:call(<0.441.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 12:54:11.022 [error] <0.660.0> gen_server <0.660.0> terminated with reason: {socket_error,timeout}
2019-12-04 12:54:11.023 [error] <0.660.0> CRASH REPORT Process <0.660.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 12:54:11.023 [error] <0.656.0> gen_server <0.656.0> terminated with reason: {socket_error,timeout}
2019-12-04 12:54:11.023 [error] <0.655.0> Supervisor {<0.655.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.95>, <0.656.0>, <0.658.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62112 -> 127.0.0.1:5672">>) at <0.660.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 12:54:11.024 [error] <0.655.0> Supervisor {<0.655.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.95>, <0.656.0>, <0.658.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62112 -> 127.0.0.1:5672">>) at <0.660.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 12:54:11.024 [error] <0.656.0> CRASH REPORT Process <0.656.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-04 12:54:11.025 [error] <0.654.0> Supervisor {<0.654.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.655.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.656.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-04 12:54:11.028 [error] <0.654.0> Supervisor {<0.654.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.655.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.656.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-04 12:54:11.028 [error] <0.651.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.656.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 12:54:11.029 [error] <0.651.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.656.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-04 12:54:11.029 [error] <0.418.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.651.0> exit with reason no such process or port in call to gen_server:call(<0.656.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-04 13:17:30.444 [error] <0.1355.0> gen_server <0.1355.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid result returned from RailwayUiWeb.MessageLive.SearchComponent.update/2.\n\nExpected {:ok, socket}, got: {:noreply, #Phoenix.LiveView.Socket<assigns: %{search: %RailwayUiWeb.MessageLive.Index.Search{query: nil, value: nil}}, changed: %{messages: true, search: true, state: true, view: true}, endpoint: RailwayUiWeb.Endpoint, id: \"phx-QgeM8f7c\", parent_pid: nil, view: RailwayUiWeb.ConsumedMessageLive.Index, ...>}...">>} in 'Elixir.Phoenix.LiveView.Utils':'maybe_call_update!'/3 line 206
2019-12-04 13:17:30.446 [error] <0.1355.0> CRASH REPORT Process <0.1355.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid result returned from RailwayUiWeb.MessageLive.SearchComponent.update/2.\n\nExpected {:ok, socket}, got: {:noreply, #Phoenix.LiveView.Socket<assigns: %{search: %RailwayUiWeb.MessageLive.Index.Search{query: nil, value: nil}}, changed: %{messages: true, search: true, state: true, view: true}, endpoint: RailwayUiWeb.Endpoint, id: \"phx-QgeM8f7c\", parent_pid: nil, view: RailwayUiWeb.ConsumedMessageLive.Index, ...>}...">>} in 'Elixir.Phoenix.LiveView.Utils':'maybe_call_update!'/3 line 206
2019-12-04 13:17:30.447 [error] <0.506.0> Supervisor {<0.506.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1355.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid result returned from RailwayUiWeb.MessageLive.SearchComponent.update/2.\n\nExpected {:ok, socket}, got: {:noreply, #Phoenix.LiveView.Socket<assigns: %{search: %RailwayUiWeb.MessageLive.Index.Search{query: nil, value: nil}}, changed: %{messages: true, search: true, state: true, view: true}, endpoint: RailwayUiWeb.Endpoint, id: \"phx-QgeM8f7c\", parent_pid: nil, view: RailwayUiWeb.ConsumedMessageLive.Index, ...>}...">>} in 'Elixir.Phoenix.LiveView.Utils':'maybe_call_update!'/3 line 206 in context child_terminated
2019-12-04 13:17:30.548 [error] <0.1332.0> CRASH REPORT Process <0.1332.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid result returned from RailwayUiWeb.MessageLive.SearchComponent.update/2.\n\nExpected {:ok, socket}, got: {:noreply, #Phoenix.LiveView.Socket<assigns: %{search: %RailwayUiWeb.MessageLive.Index.Search{query: nil, value: nil}}, changed: %{messages: true, search: true, state: true, view: true}, endpoint: RailwayUiWeb.Endpoint, id: \"phx-xygTlORw\", parent_pid: nil, view: RailwayUiWeb.ConsumedMessageLive.Index, ....">>},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 13:17:30.665 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1330.0>,1,<0.1332.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid result returned from RailwayUiWeb.MessageLive.SearchComponent.update/2.\n\nExpected {:ok, socket}, got: {:noreply, #Phoenix.LiveView.Socket<assigns: %{search: %RailwayUiWeb.MessageLive.Index.Search{query: nil, value: nil}}, changed: %{messages: true, search: true, state: true, view: true}, endpoint: RailwayUiWeb.Endpoint, ...">>},...},...},...]},...}}
2019-12-04 13:17:40.582 [error] <0.1369.0> CRASH REPORT Process <0.1369.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @view not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:search, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 13:17:40.675 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1367.0>,1,<0.1369.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @view not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:search, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-04 13:18:14.492 [error] <0.1403.0> CRASH REPORT Process <0.1403.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @view not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:search, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 13:18:14.513 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1401.0>,1,<0.1403.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @view not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:search, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-04 13:24:14.470 [error] <0.1751.0> gen_server <0.1751.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:socket, :view_module, :view_template]\n">>} in 'Elixir.Phoenix.LiveView.Engine':'fetch_assign!'/2 line 769
2019-12-04 13:24:14.470 [error] <0.1751.0> CRASH REPORT Process <0.1751.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:socket, :view_module, :view_template]\n">>} in 'Elixir.Phoenix.LiveView.Engine':'fetch_assign!'/2 line 769
2019-12-04 13:24:14.471 [error] <0.508.0> Supervisor {<0.508.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1751.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:socket, :view_module, :view_template]\n">>} in 'Elixir.Phoenix.LiveView.Engine':'fetch_assign!'/2 line 769 in context child_terminated
2019-12-04 13:24:14.527 [error] <0.1728.0> CRASH REPORT Process <0.1728.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,769}]},{'Elixir.RailwayUiWeb.MessageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 13:24:14.537 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1726.0>,1,<0.1728.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @search not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',...},...]},...},...]},...}}
2019-12-04 13:32:01.210 [error] <0.2284.0> gen_server <0.2284.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2019-12-04 13:32:01.212 [error] <0.2284.0> CRASH REPORT Process <0.2284.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2019-12-04 13:32:01.213 [error] <0.505.0> Supervisor {<0.505.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.2284.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99 in context child_terminated
2019-12-04 13:32:05.973 [error] <0.2291.0> gen_server <0.2291.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2019-12-04 13:32:05.978 [error] <0.2291.0> CRASH REPORT Process <0.2291.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2019-12-04 13:32:05.979 [error] <0.507.0> Supervisor {<0.507.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.2291.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99 in context child_terminated
2019-12-04 13:32:09.618 [error] <0.2292.0> gen_server <0.2292.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2019-12-04 13:32:09.622 [error] <0.2292.0> CRASH REPORT Process <0.2292.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2019-12-04 13:32:09.623 [error] <0.506.0> Supervisor {<0.506.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.2292.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99 in context child_terminated
2019-12-04 13:32:16.955 [error] <0.2298.0> gen_server <0.2298.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2019-12-04 13:32:16.957 [error] <0.2298.0> CRASH REPORT Process <0.2298.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99
2019-12-04 13:32:16.958 [error] <0.506.0> Supervisor {<0.506.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.2298.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Phoenix.HTML.Safe',value => {error,refused}} in 'Elixir.Phoenix.HTML.Safe.Tuple':to_iodata/1 line 99 in context child_terminated
2019-12-04 13:44:14.679 [error] <0.1042.0> CRASH REPORT Process <0.1042.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"nil given for :blah. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.blah)">>},[{'Elixir.Ecto.Query.Builder.Filter','kw!',7,[{file,"lib/ecto/query/builder/filter.ex"},{line,129}]},{'Elixir.Ecto.Query.Builder.Filter','kw!',3,[{file,"lib/ecto/query/builder/filter.ex"},{line,122}]},{'Elixir.Ecto.Query.Builder.Filter','filter!',6,[{file,"lib/ecto/query/b..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 13:44:14.797 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1041.0>,1,<0.1042.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"nil given for :blah. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.blah)">>},[{'Elixir.Ecto.Query.Builder.Filter','kw!',7,[{file,"lib/ecto/query/builder/filter.ex"},{line,129}]},{'Elixir.Ecto.Query.Builder.Filter','kw!',3,[{file,"lib/ecto/query/builder/filter.ex"},{line,...}]},...]},...},...]},...}}
2019-12-04 13:44:41.983 [error] <0.1075.0> CRASH REPORT Process <0.1075.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"nil given for :uuid. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.uuid)">>},[{'Elixir.Ecto.Query.Builder.Filter','kw!',7,[{file,"lib/ecto/query/builder/filter.ex"},{line,129}]},{'Elixir.Ecto.Query.Builder.Filter','kw!',3,[{file,"lib/ecto/query/builder/filter.ex"},{line,122}]},{'Elixir.Ecto.Query.Builder.Filter','filter!',6,[{file,"lib/ecto/query/b..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 13:44:41.990 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1073.0>,1,<0.1075.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"nil given for :uuid. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.uuid)">>},[{'Elixir.Ecto.Query.Builder.Filter','kw!',7,[{file,"lib/ecto/query/builder/filter.ex"},{line,129}]},{'Elixir.Ecto.Query.Builder.Filter','kw!',3,[{file,"lib/ecto/query/builder/filter.ex"},{line,...}]},...]},...},...]},...}}
2019-12-04 13:44:56.066 [error] <0.1108.0> CRASH REPORT Process <0.1108.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"nil given for :uuid. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.uuid)">>},[{'Elixir.Ecto.Query.Builder.Filter','kw!',7,[{file,"lib/ecto/query/builder/filter.ex"},{line,129}]},{'Elixir.Ecto.Query.Builder.Filter','kw!',3,[{file,"lib/ecto/query/builder/filter.ex"},{line,122}]},{'Elixir.Ecto.Query.Builder.Filter','filter!',6,[{file,"lib/ecto/query/b..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-04 13:44:56.075 [error] <0.383.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1106.0>,1,<0.1108.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"nil given for :uuid. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.uuid)">>},[{'Elixir.Ecto.Query.Builder.Filter','kw!',7,[{file,"lib/ecto/query/builder/filter.ex"},{line,129}]},{'Elixir.Ecto.Query.Builder.Filter','kw!',3,[{file,"lib/ecto/query/builder/filter.ex"},{line,...}]},...]},...},...]},...}}
2019-12-04 13:54:57.349 [error] <0.1016.0> gen_server <0.1016.0> terminated with reason: {'module could not be loaded',[{nil,query,[],[]},{'Elixir.RailwayUiWeb.MessageView','search_component.html',1,[{file,"lib/railway_ui_web/templates/message/search_component.html.leex"},{line,3}]},{'Elixir.Phoenix.LiveView.Utils',to_rendered,2,[{file,"lib/phoenix_live_view/utils.ex"},{line,70}]},{'Elixir.Phoenix.LiveView.Diff',render_component,7,[{file,"lib/phoenix_live_view/diff.ex"},{line,426}]},{'Elixir.Phoenix.LiveView.Diff',with_component,5,[{file,"lib/phoenix_live_view/diff.ex"},{line,126}]},...]}
2019-12-04 13:54:57.383 [error] <0.1016.0>@nil:query CRASH REPORT Process <0.1016.0> with 0 neighbours crashed with reason: call to undefined function nil:query()
2019-12-04 13:54:57.383 [error] <0.510.0>@nil:query Supervisor {<0.510.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1016.0> exit with reason call to undefined function nil:query() in context child_terminated
