2019-11-06 08:31:59.818 [error] <0.537.0> CRASH REPORT Process <0.537.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"purpose">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.819 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.819 [error] <0.535.0> CRASH REPORT Process <0.535.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_met...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.537.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.536.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"purpose">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.535.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.499.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_met...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.534.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.498.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:34:48.776 [error] <0.513.0> CRASH REPORT Process <0.513.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:34:48.800 [error] <0.513.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.509.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:00.674 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:00.675 [error] <0.534.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.522.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:07.847 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:07.847 [error] <0.547.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.543.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:47.236 [error] <0.577.0> CRASH REPORT Process <0.577.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.RailwayUiWeb.ConsumedMessageController',reason => nil},[{'Elixir.RailwayUiWeb.ConsumedMessageController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.RailwayUiWeb.Endpoint',plug_builder_call,2,[{file,"lib/railway_ui_web/endpoint.ex"},{line,1}]},{'Elixir.RailwayUiWeb.Endpoint','call (overridable 3)',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:47.237 [error] <0.577.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.575.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.RailwayUiWeb.ConsumedMessageController',reason => nil},[{'Elixir.RailwayUiWeb.ConsumedMessageController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.RailwayUiWeb.Endpoint',plug_builder_call,2,[{file,"lib/railway_ui_web/endpoint.ex"},{line,1}]},{'Elixir.RailwayUiWeb.Endpoint','call (overridable 3)',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:11.768 [error] <0.590.0> CRASH REPORT Process <0.590.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:11.768 [error] <0.590.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.589.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:34.611 [error] <0.617.0> CRASH REPORT Process <0.617.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:34.612 [error] <0.617.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.616.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:38.424 [error] <0.638.0> CRASH REPORT Process <0.638.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:38.425 [error] <0.638.0> Cowboy stream 4 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.616.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:47.193 [error] <0.648.0> CRASH REPORT Process <0.648.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:47.193 [error] <0.648.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.646.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:53.603 [error] <0.667.0> CRASH REPORT Process <0.667.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:53.604 [error] <0.667.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.660.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:24.558 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:24.580 [error] <0.525.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.523.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:32.335 [error] <0.533.0> CRASH REPORT Process <0.533.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:32.336 [error] <0.533.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.532.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:36.326 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:36.340 [error] <0.649.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.648.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:40.275 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:40.275 [error] <0.664.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.648.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:56.124 [error] <0.674.0> CRASH REPORT Process <0.674.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => get_consumed_messages,message => nil,module => nil,reason => nil},[{nil,get_consumed_messages,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,1}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:56.124 [error] <0.674.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.673.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => get_consumed_messages,message => nil,module => nil,reason => nil},[{nil,get_consumed_messages,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,1}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:45:39.304 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_messages_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_messages_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:45:39.304 [error] <0.753.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.751.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_messages_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_messages_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:25.000 [error] <0.790.0> CRASH REPORT Process <0.790.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:25.010 [error] <0.790.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.789.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:32.811 [error] <0.811.0> CRASH REPORT Process <0.811.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:32.812 [error] <0.811.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.810.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:33.670 [error] <0.830.0> CRASH REPORT Process <0.830.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:33.672 [error] <0.830.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.810.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-12 08:42:53.761 [error] <0.49.0> Loading of /Users/sophie.debenedetto/Dev/railway_hex/railway_ui/_build/test/lib/jason/ebin/Elixir.JASON.beam failed: badfile
2019-11-12 08:42:53.761 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.JASON':
  BEAM file exists but it defines a module named Elixir.Jason

2019-11-29 10:01:59.544 [error] <0.2770.0> gen_server <0.2770.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:01:59.544 [error] <0.2772.0> gen_server <0.2772.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:01:59.545 [error] <0.2771.0> gen_server <0.2771.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:04:16.924 [error] <0.493.0> gen_server <0.493.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:04:16.924 [error] <0.496.0> gen_server <0.496.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:04:16.924 [error] <0.499.0> gen_server <0.499.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:04:16.924 [error] <0.495.0> gen_server <0.495.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:04:16.925 [error] <0.491.0> gen_server <0.491.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:04:16.925 [error] <0.492.0> gen_server <0.492.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-11-29 10:07:03.556 [error] <0.1994.0>@Elixir.RailwayIpc.Application:children:11 CRASH REPORT Process <0.1994.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.RailwayIpc.Application':children(nil, dev) line 11 in application_master:init/4 line 138
2019-11-29 10:09:15.482 [error] <0.4388.0>@Elixir.RailwayIpc.Application:children:11 CRASH REPORT Process <0.4388.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.RailwayIpc.Application':children(nil, dev) line 11 in application_master:init/4 line 138
2019-11-29 14:21:13.729 [error] <0.899.0> CRASH REPORT Process <0.899.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.PublishedMessagesLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,72}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-29 14:21:13.822 [error] <0.621.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.898.0>,1,<0.899.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.PublishedMessagesLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',render,...},...]},...},...]},...}}
2019-11-29 14:21:31.234 [error] <0.936.0> CRASH REPORT Process <0.936.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_message_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_message_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0....">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-29 14:21:31.248 [error] <0.621.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.934.0>,1,<0.936.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_message_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_message_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => ...,...}},...},...],...},...]},...},...]},...}}
2019-11-29 14:21:52.364 [error] <0.959.0> CRASH REPORT Process <0.959.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => live_published_message_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',live_published_message_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,applicatio...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-29 14:21:52.443 [error] <0.621.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.958.0>,1,<0.959.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => live_published_message_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',live_published_message_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,...}},...},...],...},...]},...},...]},...}}
2019-11-29 14:22:23.738 [error] <0.982.0> CRASH REPORT Process <0.982.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action :index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.PublishedMessagesLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"lib/railway_ui_web/templates/..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-29 14:22:23.745 [error] <0.621.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.980.0>,1,<0.982.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action :index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.PublishedMessagesLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView',...},...]},...},...]},...}}
2019-11-29 14:28:57.589 [error] <0.1296.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.1296.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-11-29 14:28:57.594 [error] <0.1296.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event CRASH REPORT Process <0.1296.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"#{message.uuid}">>,<<"...">> => ...,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => []},changed => #{},'connected?' => ...,...})
2019-11-29 14:28:57.595 [error] <0.745.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event Supervisor {<0.745.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1296.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"#{message.uuid}">>,<<"...">> => ...,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => []},changed => #{},'connected?' => ...,...}) in context child_terminated
2019-11-29 14:30:08.437 [error] <0.1364.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.1364.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-11-29 14:30:08.439 [error] <0.1364.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event CRASH REPORT Process <0.1364.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"45ff7216-4cb6-4590-9bcf-a...">>,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => []},changed => #{},'connected?' => ...,...})
2019-11-29 14:30:08.439 [error] <0.745.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event Supervisor {<0.745.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1364.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"45ff7216-4cb6-4590-9bcf-a...">>,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => []},changed => #{},'connected?' => ...,...}) in context child_terminated
2019-11-29 14:30:25.740 [error] <0.1369.0>@Elixir.Phoenix.LiveView.Channel:handle_info:89 gen_server <0.1369.0> terminated with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event/3 from 'Elixir.Phoenix.LiveView.Channel':handle_info/2 line 89
2019-11-29 14:30:25.741 [error] <0.1369.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event CRASH REPORT Process <0.1369.0> with 0 neighbours crashed with reason: call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"45ff7216-4cb6-4590-9bcf-a...">>,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => []},changed => #{},'connected?' => ...,...})
2019-11-29 14:30:25.742 [error] <0.746.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event Supervisor {<0.746.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1369.0> exit with reason call to undefined function 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"45ff7216-4cb6-4590-9bcf-a...">>,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{messages => []},changed => #{},'connected?' => ...,...}) in context child_terminated
2019-11-29 14:48:41.001 [error] <0.1537.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:request_data:23 gen_server <0.1537.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':request_data(#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{current_user => #{learn_uuid => <<...>>},...},...}) line 23
2019-11-29 14:48:41.029 [error] <0.1537.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:request_data:23 CRASH REPORT Process <0.1537.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':request_data(#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{current_user => #{learn_uuid => <<...>>},...},...}) line 23
2019-11-29 14:48:41.029 [error] <0.744.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:request_data:23 Supervisor {<0.744.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.1537.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':request_data(#{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{current_user => #{learn_uuid => <<...>>},...},...}) line 23 in context child_terminated
2019-11-29 14:52:54.358 [error] <0.1584.0> CRASH REPORT Process <0.1584.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @conn not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:current_user_uuid, :messages, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-29 14:52:54.365 [error] <0.621.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1582.0>,1,<0.1584.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @conn not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:current_user_uuid, :messages, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-11-29 14:57:32.337 [error] <0.1623.0> CRASH REPORT Process <0.1623.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @conn not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:current_user_uuid, :flash, :messages, :socket, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-29 14:57:32.344 [error] <0.621.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.1621.0>,1,<0.1623.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @conn not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:current_user_uuid, :flash, :messages, :socket, :view_module, :view_template]\n">>},[...]},...},...]},...}}
2019-11-29 15:06:09.585 [error] <0.4731.0> gen_server <0.4731.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 28062,message => nil,postgres => #{code => not_null_violation,column => <<"exchange">>,detail => <<"Failing row contains (2fa6084d-b525-4c0f-9064-e20eca56590f, LearnIpc::Commands::RepublishMessage, 1f4c4051-fe12-41cf-a39a-49f794f6b333, d233d296-5d52-4a58-bb69-7fc1af7a74e9, ...">>,...},...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-29 15:06:09.585 [error] <0.4731.0> CRASH REPORT Process <0.4731.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 28062,message => nil,postgres => #{code => not_null_violation,column => <<"exchange">>,detail => <<"Failing row contains (2fa6084d-b525-4c0f-9064-e20eca56590f, LearnIpc::Commands::RepublishMessage, 1f4c4051-fe12-41cf-a39a-49f794f6b333, d233d296-5d52-4a58-bb69-7fc1af7a74e9, ...">>,...},...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2019-11-29 15:06:09.586 [error] <0.4588.0> Supervisor {<0.4588.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.4731.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => #{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 28062,message => nil,postgres => #{code => not_null_violation,column => <<"exchange">>,detail => <<"Failing row contains (2fa6084d-b525-4c0f-9064-e20eca56590f, LearnIpc::Commands::RepublishMessage, 1f4c4051-fe12-41cf-a39a-49f794f6b333, d233d296-5d52-4a58-bb69-7fc1af7a74e9, ...">>,...},...}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2019-11-29 15:10:29.725 [error] <0.4824.0> CRASH REPORT Process <0.4824.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_message_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_message_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0....">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-29 15:10:29.825 [error] <0.4476.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4822.0>,1,<0.4824.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_message_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_message_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,...}},...},...],...},...]},...},...]},...}}
2019-11-29 16:36:19.227 [error] <0.388.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.389.0> exit with reason normal in context child_terminated
2019-11-29 16:36:39.548 [error] <0.388.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.608.0> exit with reason normal in context child_terminated
2019-11-30 07:53:54.052 [error] <0.548.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event:20 gen_server <0.548.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"published_message_uuid">> => <<"eb41f789-fde6-4152-b130-0cac11c7e034">>}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{current_user_uuid => <<"c07a9c36...">>,...},...}) line 20
2019-11-30 07:53:54.076 [error] <0.548.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event:20 CRASH REPORT Process <0.548.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"published_message_uuid">> => <<"eb41f789-fde6-4152-b130-0cac11c7e034">>}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{current_user_uuid => <<"c07a9c36...">>,...},...}) line 20
2019-11-30 07:53:54.076 [error] <0.434.0>@Elixir.RailwayUiWeb.PublishedMessagesLive.Index:handle_event:20 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.548.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessagesLive.Index':handle_event(<<"republish">>, #{<<"published_message_uuid">> => <<"eb41f789-fde6-4152-b130-0cac11c7e034">>}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{current_user_uuid => <<"c07a9c36...">>,...},...}) line 20 in context child_terminated
