2019-12-02 00:01:45.038 [error] <0.2329.0> gen_server <0.2329.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:01:45.038 [error] <0.2329.0> CRASH REPORT Process <0.2329.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:01:45.038 [error] <0.2325.0> gen_server <0.2325.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:01:45.040 [error] <0.2324.0> Supervisor {<0.2324.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.320>, <0.2325.0>, <0.2327.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60053 -> 127.0.0.1:5672">>) at <0.2329.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:01:45.040 [error] <0.2324.0> Supervisor {<0.2324.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.320>, <0.2325.0>, <0.2327.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60053 -> 127.0.0.1:5672">>) at <0.2329.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:01:45.040 [error] <0.2325.0> CRASH REPORT Process <0.2325.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:01:45.041 [error] <0.2323.0> Supervisor {<0.2323.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2324.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2325.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:01:45.042 [error] <0.2323.0> Supervisor {<0.2323.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2324.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2325.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:01:45.042 [error] <0.2320.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:01:45.042 [error] <0.2320.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:01:45.043 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2320.0> exit with reason no such process or port in call to gen_server:call(<0.2325.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 00:55:51.027 [error] <0.2350.0> gen_server <0.2350.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:55:51.027 [error] <0.2350.0> CRASH REPORT Process <0.2350.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:55:51.027 [error] <0.2346.0> gen_server <0.2346.0> terminated with reason: {socket_error,timeout}
2019-12-02 00:55:51.028 [error] <0.2345.0> Supervisor {<0.2345.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.321>, <0.2346.0>, <0.2348.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60100 -> 127.0.0.1:5672">>) at <0.2350.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:55:51.028 [error] <0.2345.0> Supervisor {<0.2345.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.321>, <0.2346.0>, <0.2348.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60100 -> 127.0.0.1:5672">>) at <0.2350.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:55:51.029 [error] <0.2346.0> CRASH REPORT Process <0.2346.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 00:55:51.030 [error] <0.2341.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:55:51.044 [error] <0.2341.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 00:55:51.044 [error] <0.2344.0> Supervisor {<0.2344.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2345.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2346.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 00:55:51.044 [error] <0.2344.0> Supervisor {<0.2344.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2345.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2346.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 00:55:51.044 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2341.0> exit with reason no such process or port in call to gen_server:call(<0.2346.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 01:49:57.042 [error] <0.2378.0> gen_server <0.2378.0> terminated with reason: {socket_error,timeout}
2019-12-02 01:49:57.042 [error] <0.2378.0> CRASH REPORT Process <0.2378.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 01:49:57.043 [error] <0.2373.0> gen_server <0.2373.0> terminated with reason: {socket_error,timeout}
2019-12-02 01:49:57.043 [error] <0.2372.0> Supervisor {<0.2372.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.322>, <0.2373.0>, <0.2376.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60142 -> 127.0.0.1:5672">>) at <0.2378.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 01:49:57.044 [error] <0.2372.0> Supervisor {<0.2372.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.322>, <0.2373.0>, <0.2376.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60142 -> 127.0.0.1:5672">>) at <0.2378.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 01:49:57.044 [error] <0.2373.0> CRASH REPORT Process <0.2373.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 01:49:57.045 [error] <0.2368.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 01:49:57.045 [error] <0.2368.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2372.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2373.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2372.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2373.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 01:49:57.054 [error] <0.2371.0> Supervisor {<0.2371.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.2372.0> exit with reason shutdown in context shutdown_error
2019-12-02 01:49:57.054 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2368.0> exit with reason no such process or port in call to gen_server:call(<0.2373.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 02:31:06.037 [error] <0.2400.0> gen_server <0.2400.0> terminated with reason: {socket_error,timeout}
2019-12-02 02:31:06.037 [error] <0.2400.0> CRASH REPORT Process <0.2400.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 02:31:06.037 [error] <0.2395.0> gen_server <0.2395.0> terminated with reason: {socket_error,timeout}
2019-12-02 02:31:06.040 [error] <0.2394.0> Supervisor {<0.2394.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.323>, <0.2395.0>, <0.2398.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60193 -> 127.0.0.1:5672">>) at <0.2400.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 02:31:06.041 [error] <0.2394.0> Supervisor {<0.2394.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.323>, <0.2395.0>, <0.2398.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60193 -> 127.0.0.1:5672">>) at <0.2400.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 02:31:06.041 [error] <0.2395.0> CRASH REPORT Process <0.2395.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 02:31:06.042 [error] <0.2390.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 02:31:06.059 [error] <0.2390.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 02:31:06.059 [error] <0.2393.0> Supervisor {<0.2393.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2394.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2395.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 02:31:06.059 [error] <0.2393.0> Supervisor {<0.2393.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2394.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2395.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 02:31:06.059 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2390.0> exit with reason no such process or port in call to gen_server:call(<0.2395.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 03:25:12.046 [error] <0.2422.0> gen_server <0.2422.0> terminated with reason: {socket_error,timeout}
2019-12-02 03:25:12.046 [error] <0.2422.0> CRASH REPORT Process <0.2422.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 03:25:12.047 [error] <0.2417.0> Supervisor {<0.2417.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.324>, <0.2418.0>, <0.2420.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60246 -> 127.0.0.1:5672">>) at <0.2422.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 03:25:12.047 [error] <0.2417.0> Supervisor {<0.2417.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.324>, <0.2418.0>, <0.2420.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60246 -> 127.0.0.1:5672">>) at <0.2422.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 03:25:12.047 [error] <0.2418.0> gen_server <0.2418.0> terminated with reason: {socket_error,timeout}
2019-12-02 03:25:12.047 [error] <0.2418.0> CRASH REPORT Process <0.2418.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 03:25:12.047 [error] <0.2413.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 03:25:12.048 [error] <0.2416.0> Supervisor {<0.2416.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2417.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2418.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 03:25:12.048 [error] <0.2416.0> Supervisor {<0.2416.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2417.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2418.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 03:25:12.048 [error] <0.2413.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 03:25:12.049 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2413.0> exit with reason no such process or port in call to gen_server:call(<0.2418.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 04:19:18.031 [error] <0.2444.0> gen_server <0.2444.0> terminated with reason: {socket_error,timeout}
2019-12-02 04:19:18.031 [error] <0.2444.0> CRASH REPORT Process <0.2444.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 04:19:18.031 [error] <0.2440.0> gen_server <0.2440.0> terminated with reason: {socket_error,timeout}
2019-12-02 04:19:18.032 [error] <0.2439.0> Supervisor {<0.2439.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.325>, <0.2440.0>, <0.2442.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60304 -> 127.0.0.1:5672">>) at <0.2444.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 04:19:18.032 [error] <0.2439.0> Supervisor {<0.2439.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.325>, <0.2440.0>, <0.2442.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60304 -> 127.0.0.1:5672">>) at <0.2444.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 04:19:18.032 [error] <0.2440.0> CRASH REPORT Process <0.2440.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 04:19:18.034 [error] <0.2435.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 04:19:18.044 [error] <0.2435.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 04:19:18.045 [error] <0.2438.0> Supervisor {<0.2438.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2439.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2440.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 04:19:18.045 [error] <0.2438.0> Supervisor {<0.2438.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2439.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2440.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 04:19:18.045 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2435.0> exit with reason no such process or port in call to gen_server:call(<0.2440.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 05:13:24.048 [error] <0.2466.0> gen_server <0.2466.0> terminated with reason: {socket_error,timeout}
2019-12-02 05:13:24.048 [error] <0.2466.0> CRASH REPORT Process <0.2466.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 05:13:24.048 [error] <0.2461.0> gen_server <0.2461.0> terminated with reason: {socket_error,timeout}
2019-12-02 05:13:24.049 [error] <0.2460.0> Supervisor {<0.2460.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.326>, <0.2461.0>, <0.2464.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60362 -> 127.0.0.1:5672">>) at <0.2466.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 05:13:24.049 [error] <0.2460.0> Supervisor {<0.2460.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.326>, <0.2461.0>, <0.2464.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60362 -> 127.0.0.1:5672">>) at <0.2466.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 05:13:24.049 [error] <0.2461.0> CRASH REPORT Process <0.2461.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 05:13:24.049 [error] <0.2456.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 05:13:24.050 [error] <0.2456.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2460.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2461.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2460.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2461.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 05:13:24.051 [error] <0.2459.0> Supervisor {<0.2459.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.2460.0> exit with reason shutdown in context shutdown_error
2019-12-02 05:13:24.051 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2456.0> exit with reason no such process or port in call to gen_server:call(<0.2461.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 06:07:30.045 [error] <0.2488.0> gen_server <0.2488.0> terminated with reason: {socket_error,timeout}
2019-12-02 06:07:30.045 [error] <0.2488.0> CRASH REPORT Process <0.2488.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 06:07:30.045 [error] <0.2484.0> gen_server <0.2484.0> terminated with reason: {socket_error,timeout}
2019-12-02 06:07:30.046 [error] <0.2484.0> CRASH REPORT Process <0.2484.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 06:07:30.046 [error] <0.2483.0> Supervisor {<0.2483.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.327>, <0.2484.0>, <0.2486.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60423 -> 127.0.0.1:5672">>) at <0.2488.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 06:07:30.046 [error] <0.2483.0> Supervisor {<0.2483.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.327>, <0.2484.0>, <0.2486.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60423 -> 127.0.0.1:5672">>) at <0.2488.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 06:07:30.046 [error] <0.2482.0> Supervisor {<0.2482.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2483.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2484.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 06:07:30.046 [error] <0.2482.0> Supervisor {<0.2482.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2483.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2484.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 06:07:30.047 [error] <0.2479.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 06:07:30.048 [error] <0.2479.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 06:07:30.048 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2479.0> exit with reason no such process or port in call to gen_server:call(<0.2484.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:01:36.033 [error] <0.2510.0> gen_server <0.2510.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:01:36.033 [error] <0.2510.0> CRASH REPORT Process <0.2510.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:01:36.033 [error] <0.2505.0> gen_server <0.2505.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:01:36.034 [error] <0.2504.0> Supervisor {<0.2504.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.328>, <0.2505.0>, <0.2508.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60488 -> 127.0.0.1:5672">>) at <0.2510.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:01:36.034 [error] <0.2504.0> Supervisor {<0.2504.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.328>, <0.2505.0>, <0.2508.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60488 -> 127.0.0.1:5672">>) at <0.2510.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:01:36.034 [error] <0.2505.0> CRASH REPORT Process <0.2505.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:01:36.036 [error] <0.2500.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:01:36.045 [error] <0.2503.0> Supervisor {<0.2503.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2504.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2505.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:01:36.045 [error] <0.2503.0> Supervisor {<0.2503.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2504.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2505.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:01:36.045 [error] <0.2500.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:01:36.046 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2500.0> exit with reason no such process or port in call to gen_server:call(<0.2505.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:25:58.032 [error] <0.2532.0> gen_server <0.2532.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:25:58.032 [error] <0.2532.0> CRASH REPORT Process <0.2532.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:25:58.032 [error] <0.2528.0> gen_server <0.2528.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:25:58.033 [error] <0.2528.0> CRASH REPORT Process <0.2528.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:25:58.045 [error] <0.2527.0> Supervisor {<0.2527.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.329>, <0.2528.0>, <0.2530.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60525 -> 127.0.0.1:5672">>) at <0.2532.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:25:58.045 [error] <0.2527.0> Supervisor {<0.2527.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.329>, <0.2528.0>, <0.2530.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60525 -> 127.0.0.1:5672">>) at <0.2532.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:25:58.045 [error] <0.2526.0> Supervisor {<0.2526.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2527.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2528.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:25:58.045 [error] <0.2526.0> Supervisor {<0.2526.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2527.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2528.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:25:58.047 [error] <0.2523.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:25:58.047 [error] <0.2523.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:25:58.048 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2523.0> exit with reason no such process or port in call to gen_server:call(<0.2528.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 07:35:09.150 [error] <0.556.0> gen_server <0.556.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599
2019-12-02 07:35:09.163 [error] <0.556.0> CRASH REPORT Process <0.556.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599
2019-12-02 07:35:09.163 [error] <0.434.0> Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.556.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Mox.UnexpectedCallError',message => <<"no expectation defined for RailwayUi.PersistenceMock.count_published_message_search_results/2 in process #PID<0.556.0> (or in its callers [#PID<0.553.0>]) with args [\"uuid\", \"77471a02-05c8-408c-a778-a066c8cd0caa\"]">>} in 'Elixir.Mox':'__dispatch__'/4 line 599 in context child_terminated
2019-12-02 07:40:55.341 [error] <0.560.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 gen_server <0.560.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122
2019-12-02 07:40:55.356 [error] <0.560.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 CRASH REPORT Process <0.560.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122
2019-12-02 07:40:55.357 [error] <0.434.0>@Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest:-test it searches by message type/1-fun-0-:122 Supervisor 'Elixir.Phoenix.LiveView.DynamicSupervisor' had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.560.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.IndexTest':'-test it searches by message type/1-fun-0-'(<<"message_type">>, <<"CreateBatch">>, #{limit => 2,page => 2}) line 122 in context child_terminated
2019-12-02 07:49:17.023 [error] <0.2554.0> gen_server <0.2554.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:49:17.024 [error] <0.2554.0> CRASH REPORT Process <0.2554.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:49:17.024 [error] <0.2550.0> gen_server <0.2550.0> terminated with reason: {socket_error,timeout}
2019-12-02 07:49:17.025 [error] <0.2549.0> Supervisor {<0.2549.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.330>, <0.2550.0>, <0.2552.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60572 -> 127.0.0.1:5672">>) at <0.2554.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:49:17.025 [error] <0.2549.0> Supervisor {<0.2549.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.330>, <0.2550.0>, <0.2552.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60572 -> 127.0.0.1:5672">>) at <0.2554.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:49:17.025 [error] <0.2550.0> CRASH REPORT Process <0.2550.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 07:49:17.026 [error] <0.2545.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2550.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:49:17.027 [error] <0.2545.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2550.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 07:49:17.031 [error] <0.2548.0> Supervisor {<0.2548.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2549.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2550.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 07:49:17.031 [error] <0.2548.0> Supervisor {<0.2548.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2549.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2550.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 07:49:17.031 [error] <0.2548.0> Supervisor {<0.2548.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.2549.0> exit with reason shutdown in context shutdown_error
2019-12-02 07:49:17.031 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2545.0> exit with reason no such process or port in call to gen_server:call(<0.2550.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 09:51:32.021 [error] <0.2594.0> gen_server <0.2594.0> terminated with reason: {socket_error,timeout}
2019-12-02 09:51:32.022 [error] <0.2594.0> CRASH REPORT Process <0.2594.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 09:51:32.022 [error] <0.2590.0> gen_server <0.2590.0> terminated with reason: {socket_error,timeout}
2019-12-02 09:51:32.022 [error] <0.2590.0> CRASH REPORT Process <0.2590.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 09:51:32.023 [error] <0.2589.0> Supervisor {<0.2589.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.333>, <0.2590.0>, <0.2592.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60939 -> 127.0.0.1:5672">>) at <0.2594.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 09:51:32.023 [error] <0.2589.0> Supervisor {<0.2589.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.333>, <0.2590.0>, <0.2592.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60939 -> 127.0.0.1:5672">>) at <0.2594.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 09:51:32.033 [error] <0.2588.0> Supervisor {<0.2588.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2589.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2590.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 09:51:32.033 [error] <0.2585.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2590.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 09:51:32.033 [error] <0.2585.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2590.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 09:51:32.034 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2585.0> exit with reason no such process or port in call to gen_server:call(<0.2590.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 09:51:32.034 [error] <0.2588.0> Supervisor {<0.2588.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2589.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2590.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 10:49:54.003 [error] <0.2731.0> gen_server <0.2731.0> terminated with reason: {socket_error,timeout}
2019-12-02 10:49:54.004 [error] <0.2731.0> CRASH REPORT Process <0.2731.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 10:49:54.004 [error] <0.2726.0> Supervisor {<0.2726.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.340>, <0.2727.0>, <0.2729.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62715 -> 127.0.0.1:5672">>) at <0.2731.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 10:49:54.004 [error] <0.2726.0> Supervisor {<0.2726.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.340>, <0.2727.0>, <0.2729.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:62715 -> 127.0.0.1:5672">>) at <0.2731.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 10:49:54.004 [error] <0.2727.0> gen_server <0.2727.0> terminated with reason: {socket_error,timeout}
2019-12-02 10:49:54.004 [error] <0.2727.0> CRASH REPORT Process <0.2727.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 10:49:54.004 [error] <0.2725.0> Supervisor {<0.2725.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2726.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2727.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 10:49:54.005 [error] <0.2725.0> Supervisor {<0.2725.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2726.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2727.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 10:49:54.005 [error] <0.2722.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2727.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 10:49:54.005 [error] <0.2722.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2727.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 10:49:54.006 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2722.0> exit with reason no such process or port in call to gen_server:call(<0.2727.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 11:29:09.008 [error] <0.2778.0> gen_server <0.2778.0> terminated with reason: {socket_error,timeout}
2019-12-02 11:29:09.008 [error] <0.2778.0> CRASH REPORT Process <0.2778.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 11:29:09.009 [error] <0.2774.0> gen_server <0.2774.0> terminated with reason: {socket_error,timeout}
2019-12-02 11:29:09.010 [error] <0.2773.0> Supervisor {<0.2773.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.341>, <0.2774.0>, <0.2776.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63102 -> 127.0.0.1:5672">>) at <0.2778.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 11:29:09.010 [error] <0.2773.0> Supervisor {<0.2773.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.341>, <0.2774.0>, <0.2776.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63102 -> 127.0.0.1:5672">>) at <0.2778.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 11:29:09.010 [error] <0.2774.0> CRASH REPORT Process <0.2774.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 11:29:09.012 [error] <0.2772.0> Supervisor {<0.2772.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2773.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2774.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 11:29:09.013 [error] <0.2772.0> Supervisor {<0.2772.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2773.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2774.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 11:29:09.013 [error] <0.2769.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2774.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 11:29:09.014 [error] <0.2769.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2774.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 11:29:09.014 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2769.0> exit with reason no such process or port in call to gen_server:call(<0.2774.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 11:31:58.020 [error] <0.2800.0> gen_server <0.2800.0> terminated with reason: {socket_error,timeout}
2019-12-02 11:31:58.020 [error] <0.2800.0> CRASH REPORT Process <0.2800.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 11:31:58.021 [error] <0.2796.0> gen_server <0.2796.0> terminated with reason: {socket_error,timeout}
2019-12-02 11:31:58.022 [error] <0.2795.0> Supervisor {<0.2795.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.342>, <0.2796.0>, <0.2798.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63212 -> 127.0.0.1:5672">>) at <0.2800.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 11:31:58.023 [error] <0.2795.0> Supervisor {<0.2795.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.342>, <0.2796.0>, <0.2798.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63212 -> 127.0.0.1:5672">>) at <0.2800.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 11:31:58.023 [error] <0.2796.0> CRASH REPORT Process <0.2796.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 11:31:58.025 [error] <0.2794.0> Supervisor {<0.2794.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2795.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2796.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 11:31:58.026 [error] <0.2794.0> Supervisor {<0.2794.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2795.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2796.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 11:31:58.026 [error] <0.2791.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2796.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 11:31:58.026 [error] <0.2791.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2796.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 11:31:58.027 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2791.0> exit with reason no such process or port in call to gen_server:call(<0.2796.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 12:11:06.002 [error] <0.2822.0> gen_server <0.2822.0> terminated with reason: {socket_error,timeout}
2019-12-02 12:11:06.002 [error] <0.2822.0> CRASH REPORT Process <0.2822.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 12:11:06.003 [error] <0.2818.0> gen_server <0.2818.0> terminated with reason: {socket_error,timeout}
2019-12-02 12:11:06.004 [error] <0.2817.0> Supervisor {<0.2817.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.343>, <0.2818.0>, <0.2820.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63261 -> 127.0.0.1:5672">>) at <0.2822.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 12:11:06.004 [error] <0.2817.0> Supervisor {<0.2817.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.343>, <0.2818.0>, <0.2820.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63261 -> 127.0.0.1:5672">>) at <0.2822.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 12:11:06.004 [error] <0.2818.0> CRASH REPORT Process <0.2818.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 12:11:06.005 [error] <0.2816.0> Supervisor {<0.2816.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2817.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2818.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 12:11:06.006 [error] <0.2816.0> Supervisor {<0.2816.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2817.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2818.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 12:11:06.006 [error] <0.2813.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2818.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 12:11:06.006 [error] <0.2813.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2818.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 12:11:06.007 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2813.0> exit with reason no such process or port in call to gen_server:call(<0.2818.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 13:25:04.013 [error] <0.2860.0> gen_server <0.2860.0> terminated with reason: {socket_error,timeout}
2019-12-02 13:25:04.013 [error] <0.2860.0> CRASH REPORT Process <0.2860.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 13:25:04.014 [error] <0.2855.0> Supervisor {<0.2855.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.344>, <0.2856.0>, <0.2858.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63822 -> 127.0.0.1:5672">>) at <0.2860.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 13:25:04.014 [error] <0.2855.0> Supervisor {<0.2855.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.344>, <0.2856.0>, <0.2858.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63822 -> 127.0.0.1:5672">>) at <0.2860.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 13:25:04.030 [error] <0.2856.0> gen_server <0.2856.0> terminated with reason: {socket_error,timeout}
2019-12-02 13:25:04.030 [error] <0.2856.0> CRASH REPORT Process <0.2856.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 13:25:04.031 [error] <0.2854.0> Supervisor {<0.2854.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2855.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2856.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 13:25:04.031 [error] <0.2854.0> Supervisor {<0.2854.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2855.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2856.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 13:25:04.031 [error] <0.2851.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2856.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 13:25:04.031 [error] <0.2851.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2856.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 13:25:04.031 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2851.0> exit with reason no such process or port in call to gen_server:call(<0.2856.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 13:38:46.016 [error] <0.2940.0> gen_server <0.2940.0> terminated with reason: {socket_error,timeout}
2019-12-02 13:38:46.016 [error] <0.2940.0> CRASH REPORT Process <0.2940.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 13:38:46.016 [error] <0.2936.0> gen_server <0.2936.0> terminated with reason: {socket_error,timeout}
2019-12-02 13:38:46.016 [error] <0.2936.0> CRASH REPORT Process <0.2936.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 13:38:46.017 [error] <0.2935.0> Supervisor {<0.2935.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.353>, <0.2936.0>, <0.2938.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64179 -> 127.0.0.1:5672">>) at <0.2940.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 13:38:46.017 [error] <0.2935.0> Supervisor {<0.2935.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.353>, <0.2936.0>, <0.2938.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64179 -> 127.0.0.1:5672">>) at <0.2940.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 13:38:46.017 [error] <0.2934.0> Supervisor {<0.2934.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2935.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2936.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 13:38:46.017 [error] <0.2934.0> Supervisor {<0.2934.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2935.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2936.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 13:38:46.018 [error] <0.2931.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2936.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 13:38:46.018 [error] <0.2931.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2936.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 13:38:46.019 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2931.0> exit with reason no such process or port in call to gen_server:call(<0.2936.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 13:47:52.011 [error] <0.3003.0> gen_server <0.3003.0> terminated with reason: {socket_error,timeout}
2019-12-02 13:47:52.011 [error] <0.3003.0> CRASH REPORT Process <0.3003.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 13:47:52.012 [error] <0.2999.0> gen_server <0.2999.0> terminated with reason: {socket_error,timeout}
2019-12-02 13:47:52.012 [error] <0.2998.0> Supervisor {<0.2998.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.360>, <0.2999.0>, <0.3001.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64212 -> 127.0.0.1:5672">>) at <0.3003.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 13:47:52.012 [error] <0.2998.0> Supervisor {<0.2998.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.360>, <0.2999.0>, <0.3001.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64212 -> 127.0.0.1:5672">>) at <0.3003.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 13:47:52.012 [error] <0.2999.0> CRASH REPORT Process <0.2999.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 13:47:52.013 [error] <0.2997.0> Supervisor {<0.2997.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2998.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2999.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 13:47:52.014 [error] <0.2997.0> Supervisor {<0.2997.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2998.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.2999.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 13:47:52.014 [error] <0.2994.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.2999.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 13:47:52.015 [error] <0.2994.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2999.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 13:47:52.015 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.2994.0> exit with reason no such process or port in call to gen_server:call(<0.2999.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 13:53:59.012 [error] <0.3048.0> gen_server <0.3048.0> terminated with reason: {socket_error,timeout}
2019-12-02 13:53:59.012 [error] <0.3048.0> CRASH REPORT Process <0.3048.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 13:53:59.013 [error] <0.3044.0> gen_server <0.3044.0> terminated with reason: {socket_error,timeout}
2019-12-02 13:53:59.014 [error] <0.3044.0> CRASH REPORT Process <0.3044.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 13:53:59.014 [error] <0.3042.0> Supervisor {<0.3042.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3043.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.3044.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 13:53:59.014 [error] <0.3042.0> Supervisor {<0.3042.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3043.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.3044.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 13:53:59.015 [error] <0.3043.0> Supervisor {<0.3043.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.367>, <0.3044.0>, <0.3046.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64314 -> 127.0.0.1:5672">>) at <0.3048.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 13:53:59.015 [error] <0.3043.0> Supervisor {<0.3043.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.367>, <0.3044.0>, <0.3046.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64314 -> 127.0.0.1:5672">>) at <0.3048.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 13:53:59.015 [error] <0.3039.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.3044.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 13:53:59.016 [error] <0.3039.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3044.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 13:53:59.016 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.3039.0> exit with reason no such process or port in call to gen_server:call(<0.3044.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 14:01:41.959 [error] <0.4012.0> CRASH REPORT Process <0.4012.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"c...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:01:42.025 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4011.0>,1,<0.4012.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encod...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-12-02 14:01:42.224 [error] <0.4062.0> CRASH REPORT Process <0.4062.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"li..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:01:42.231 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4011.0>,2,<0.4062.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/route..."},...]},...]},...},...]},...}}
2019-12-02 14:01:42.404 [error] <0.4063.0> CRASH REPORT Process <0.4063.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,72}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:01:42.412 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4013.0>,1,<0.4063.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...},...]},...}}
2019-12-02 14:01:47.554 [error] <0.4080.0> CRASH REPORT Process <0.4080.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,72}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:01:47.560 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4013.0>,7,<0.4080.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...},...]},...}}
2019-12-02 14:02:34.073 [error] <0.4091.0> CRASH REPORT Process <0.4091.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"li..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:02:34.085 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4090.0>,1,<0.4091.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/route..."},...]},...]},...},...]},...}}
2019-12-02 14:03:12.094 [error] <0.4118.0> CRASH REPORT Process <0.4118.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.PublishedMessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:03:12.099 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4116.0>,1,<0.4118.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.PublishedMessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoe..."},...]},...]},...},...]},...}}
2019-12-02 14:03:12.208 [error] <0.4119.0> CRASH REPORT Process <0.4119.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,72}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:03:12.216 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4117.0>,1,<0.4119.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...},...]},...}}
2019-12-02 14:03:12.310 [error] <0.4130.0> CRASH REPORT Process <0.4130.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.PublishedMessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:03:12.317 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4129.0>,1,<0.4130.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.PublishedMessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoe..."},...]},...]},...},...]},...}}
2019-12-02 14:03:17.576 [error] <0.4151.0> CRASH REPORT Process <0.4151.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"li..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:03:17.585 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4129.0>,5,<0.4151.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/route..."},...]},...]},...},...]},...}}
2019-12-02 14:03:17.983 [error] <0.4168.0> CRASH REPORT Process <0.4168.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"li..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:03:17.990 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4150.0>,1,<0.4168.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/route..."},...]},...]},...},...]},...}}
2019-12-02 14:03:18.169 [error] <0.4167.0> CRASH REPORT Process <0.4167.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,72}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:03:18.175 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4129.0>,7,<0.4167.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...},...]},...}}
2019-12-02 14:04:03.505 [error] <0.4189.0> CRASH REPORT Process <0.4189.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"lib/railway_ui_..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:04:03.509 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4187.0>,1,<0.4189.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},...]},...]},...},...]},...}}
2019-12-02 14:04:04.031 [error] <0.4205.0> CRASH REPORT Process <0.4205.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"lib/railway_ui_..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:04:04.036 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4188.0>,1,<0.4205.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},...]},...]},...},...]},...}}
2019-12-02 14:04:04.179 [error] <0.4204.0> CRASH REPORT Process <0.4204.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,72}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:04:04.183 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4187.0>,3,<0.4204.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...},...]},...}}
2019-12-02 14:04:15.048 [error] <0.4226.0> CRASH REPORT Process <0.4226.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"li..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:04:15.065 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4222.0>,1,<0.4226.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/route..."},...]},...]},...},...]},...}}
2019-12-02 14:04:15.170 [error] <0.4224.0> CRASH REPORT Process <0.4224.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoenix_live_view/static.ex"},{line,72}]},{'Elixir.Phoenix.LiveView.Controller',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:04:15.176 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4223.0>,1,<0.4224.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => '__live__',message => nil,module => 'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index',reason => nil},[{'Elixir.RailwayUiWeb.RailwayUiWeb.MessageLive.Index','__live__',[],[]},{'Elixir.Phoenix.LiveView.Static','load_live!',2,[{file,"lib/phoenix_live_view/static.ex"},{line,219}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...},...]},...}}
2019-12-02 14:04:15.482 [error] <0.4237.0> CRASH REPORT Process <0.4237.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"li..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:04:15.488 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4222.0>,2,<0.4237.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.MessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/route..."},...]},...]},...},...]},...}}
2019-12-02 14:04:20.160 [error] <0.4256.0> CRASH REPORT Process <0.4256.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.ConsumedMessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.LayoutView','app.html',1,[{file,"lib/rai..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:04:20.166 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4222.0>,4,<0.4256.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.ConsumedMessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/hel..."},...]},...]},...},...]},...}}
2019-12-02 14:04:50.248 [error] <0.4282.0> CRASH REPORT Process <0.4282.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.ConsumedMessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.MessageLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:04:50.254 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4281.0>,1,<0.4282.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.live_path/2 and action RailwayUiWeb.ConsumedMessageLive.Index. The following actions/clauses are supported:\n\n    live_path(conn_or_endpoint, RailwayUiWeb.MessageLive.Index, params \\\\ [])\n    live_path(conn_or_endpoint, RailwayUiWeb.MessageLive.Index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',...},...]},...},...]},...}}
2019-12-02 14:05:14.209 [error] <0.4318.0> CRASH REPORT Process <0.4318.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => nil,reason => nil},[{nil,render,[<<"index.html">>,#{messages => [#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.RailwayIpc.Persistence.PublishedMessage',source => <<"railway_ipc_published_messages">>,state => loaded},'__struct__' => 'Elixir.RailwayIpc.Persistence.PublishedMessage',correlation_id => <<..>>,...},...],...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:05:14.215 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4309.0>,1,<0.4318.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => nil,reason => nil},[{nil,render,[<<"index.html">>,#{messages => [#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.RailwayIpc.Persistence.PublishedMessage',source => <<"railway_ipc_published_messages">>,state => loaded},...},...],...}],...},...]},...},...]},...}}
2019-12-02 14:05:16.056 [error] <0.4354.0> CRASH REPORT Process <0.4354.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => nil,reason => nil},[{nil,render,[<<"index.html">>,#{messages => [#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.RailwayIpc.Persistence.PublishedMessage',source => <<"railway_ipc_published_messages">>,state => loaded},'__struct__' => 'Elixir.RailwayIpc.Persistence.PublishedMessage',correlation_id => <<..>>,...},...],...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:05:16.068 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4309.0>,6,<0.4354.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => nil,reason => nil},[{nil,render,[<<"index.html">>,#{messages => [#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.RailwayIpc.Persistence.PublishedMessage',source => <<"railway_ipc_published_messages">>,state => loaded},...},...],...}],...},...]},...},...]},...}}
2019-12-02 14:05:52.823 [error] <0.4364.0> CRASH REPORT Process <0.4364.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => nil,reason => nil},[{nil,render,[<<"index.html">>,#{messages => [#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.RailwayIpc.Persistence.PublishedMessage',source => <<"railway_ipc_published_messages">>,state => loaded},'__struct__' => 'Elixir.RailwayIpc.Persistence.PublishedMessage',correlation_id => <<..>>,...},...],...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:05:52.829 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4362.0>,1,<0.4364.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => nil,reason => nil},[{nil,render,[<<"index.html">>,#{messages => [#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.RailwayIpc.Persistence.PublishedMessage',source => <<"railway_ipc_published_messages">>,state => loaded},...},...],...}],...},...]},...},...]},...}}
2019-12-02 14:06:02.311 [error] <0.4387.0> CRASH REPORT Process <0.4387.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => nil,reason => nil},[{nil,render,[<<"index.html">>,#{messages => [#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.RailwayIpc.Persistence.PublishedMessage',source => <<"railway_ipc_published_messages">>,state => loaded},'__struct__' => 'Elixir.RailwayIpc.Persistence.PublishedMessage',correlation_id => <<..>>,...},...],...}],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:06:02.317 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4386.0>,1,<0.4387.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => nil,reason => nil},[{nil,render,[<<"index.html">>,#{messages => [#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.RailwayIpc.Persistence.PublishedMessage',source => <<"railway_ipc_published_messages">>,state => loaded},...},...],...}],...},...]},...},...]},...}}
2019-12-02 14:10:10.182 [error] <0.49.0> Loading of /usr/local/Cellar/elixir/1.9.0/bin/../lib/elixir/ebin/Elixir.Uri.beam failed: badfile
2019-12-02 14:10:10.186 [error] <0.49.0> Loading of /usr/local/Cellar/elixir/1.9.0/bin/../lib/elixir/ebin/Elixir.Uri.beam failed: badfile
2019-12-02 14:10:10.192 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.Uri':
  BEAM file exists but it defines a module named Elixir.URI

2019-12-02 14:10:10.192 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.Uri':
  BEAM file exists but it defines a module named Elixir.URI

2019-12-02 14:21:05.838 [error] <0.4531.0> CRASH REPORT Process <0.4531.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => get_message_type,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State'},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',get_message_type,['Elixir.RailwayUi.PublishedMessage'],[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,113}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',new,2,[{file,"lib/railway_ui_web/live/message_live/index/sta..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:21:05.843 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4530.0>,1,<0.4531.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => get_message_type,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State'},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',get_message_type,['Elixir.RailwayUi.PublishedMessage'],[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,113}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',...},...]},...},...]},...}}
2019-12-02 14:21:42.697 [error] <0.4560.0> CRASH REPORT Process <0.4560.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"published_messages">>,all,[#{limit => 2,page => 1}]],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',load_messages,1,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,19}]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"l..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:21:42.725 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4558.0>,1,<0.4560.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"published_messages">>,all,[#{limit => 2,page => 1}]],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',load_messages,1,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,19}]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/ind..."},...]},...]},...},...]},...}}
2019-12-02 14:21:51.908 [error] <0.4581.0> CRASH REPORT Process <0.4581.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"published_messages">>,all,[#{limit => 2,page => 1}]],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',load_messages,1,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,19}]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,20}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"l..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:21:51.915 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4580.0>,1,<0.4581.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"published_messages">>,all,[#{limit => 2,page => 1}]],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',load_messages,1,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,19}]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/ind..."},...]},...]},...},...]},...}}
2019-12-02 14:28:18.129 [error] <0.4719.0> CRASH REPORT Process <0.4719.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => new,message => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State',reason => nil},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',new,[<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,22}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/ut..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:28:18.143 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4717.0>,1,<0.4719.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => new,message => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State',reason => nil},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',new,[<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,22}]},{'Elixir.Phoenix.LiveView.Utils',...},...]},...},...]},...}}
2019-12-02 14:28:18.865 [error] <0.4732.0> gen_server <0.4732.0> terminated with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => new,message => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State',reason => nil},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',new,[<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,22}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/util..."},...]},...]}
2019-12-02 14:28:18.869 [error] <0.4732.0> CRASH REPORT Process <0.4732.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => new,message => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State',reason => nil},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',new,[<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,22}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/util..."},...]},...]}
2019-12-02 14:28:18.869 [error] <0.512.0> Supervisor {<0.512.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.4732.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => new,message => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State',reason => nil},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',new,[<<"1f4c4051-fe12-41cf-a39a-49f794f6b333">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',mount,2,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,22}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/util..."},...]},...]} in context child_terminated
2019-12-02 14:28:51.330 [error] <0.511.0> Supervisor {<0.511.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.4689.0> exit with reason killed in context child_terminated
2019-12-02 14:28:51.473 [error] <0.4745.0> CRASH REPORT Process <0.4745.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => nil,reason => nil},[{nil,all,[#{limit => 2,page => 1}],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',handle_params,3,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,76}]},{'Elixir.Phoenix.LiveView.Static','call_mount_and_handle_params!',6,[{file,"lib/phoenix_live_view/static.ex"},{line,231}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoe..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:28:51.480 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4744.0>,1,<0.4745.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => nil,reason => nil},[{nil,all,[#{limit => 2,page => 1}],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',handle_params,3,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,76}]},{'Elixir.Phoenix.LiveView.Static','call_mount_and_handle_params!',6,[{file,"lib/phoenix_live_view/..."},...]},...]},...},...]},...}}
2019-12-02 14:31:35.019 [error] <0.3095.0> gen_server <0.3095.0> terminated with reason: {socket_error,timeout}
2019-12-02 14:31:35.019 [error] <0.3095.0> CRASH REPORT Process <0.3095.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 14:31:35.020 [error] <0.3091.0> gen_server <0.3091.0> terminated with reason: {socket_error,timeout}
2019-12-02 14:31:35.020 [error] <0.3091.0> CRASH REPORT Process <0.3091.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 14:31:35.020 [error] <0.3089.0> Supervisor {<0.3089.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3090.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.3091.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 14:31:35.020 [error] <0.3089.0> Supervisor {<0.3089.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.3090.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.3091.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 14:31:35.020 [error] <0.3090.0> Supervisor {<0.3090.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.374>, <0.3091.0>, <0.3093.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64361 -> 127.0.0.1:5672">>) at <0.3095.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 14:31:35.020 [error] <0.3090.0> Supervisor {<0.3090.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.374>, <0.3091.0>, <0.3093.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64361 -> 127.0.0.1:5672">>) at <0.3095.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 14:31:35.021 [error] <0.3086.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.3091.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 14:31:35.021 [error] <0.3086.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3091.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 14:31:35.022 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.3086.0> exit with reason no such process or port in call to gen_server:call(<0.3091.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 14:42:34.753 [error] <0.4937.0> CRASH REPORT Process <0.4937.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => nil,reason => nil},[{nil,all,[#{limit => 2,page => 1}],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',handle_params,3,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,52}]},{'Elixir.Phoenix.LiveView.Static','call_mount_and_handle_params!',6,[{file,"lib/phoenix_live_view/static.ex"},{line,231}]},{'Elixir.Phoenix.LiveView.Static',render,3,[{file,"lib/phoe..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:42:34.759 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4936.0>,1,<0.4937.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => nil,reason => nil},[{nil,all,[#{limit => 2,page => 1}],[]},{'Elixir.RailwayUiWeb.MessageLive.Index',handle_params,3,[{file,"lib/railway_ui_web/live/message_live/index.ex"},{line,52}]},{'Elixir.Phoenix.LiveView.Static','call_mount_and_handle_params!',6,[{file,"lib/phoenix_live_view/..."},...]},...]},...},...]},...}}
2019-12-02 14:44:36.351 [error] <0.4950.0> CRASH REPORT Process <0.4950.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArithmeticError',message => <<"bad argument in arithmetic expression">>},[{'Elixir.RailwayUiWeb.MessageView','pagination.html',1,[{file,"lib/railway_ui_web/templates/message/pagination.html.leex"},{line,4}]},{'Elixir.RailwayUiWeb.MessageView','index.html',1,[{file,"lib/railway_ui_web/templates/message/index.html.leex"},{line,36}]},{'Elixir.Phoenix.LiveView.Utils',to_rendered,2,[{file,"lib/phoenix_live_view/utils.ex"},{line,70}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:44:36.356 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4948.0>,1,<0.4950.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArithmeticError',message => <<"bad argument in arithmetic expression">>},[{'Elixir.RailwayUiWeb.MessageView','pagination.html',1,[{file,"lib/railway_ui_web/templates/message/pagination.html.leex"},{line,4}]},{'Elixir.RailwayUiWeb.MessageView','index.html',1,[{file,"lib/railway_ui_web/templates/message/index.html.leex"},{line,36}]},{'Elixir.Phoenix.LiveView.Utils',...},...]},...},...]},...}}
2019-12-02 14:45:06.388 [error] <0.4977.0> CRASH REPORT Process <0.4977.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArithmeticError',message => <<"bad argument in arithmetic expression">>},[{'Elixir.RailwayUiWeb.MessageView','pagination.html',1,[{file,"lib/railway_ui_web/templates/message/pagination.html.leex"},{line,4}]},{'Elixir.RailwayUiWeb.MessageView','index.html',1,[{file,"lib/railway_ui_web/templates/message/index.html.leex"},{line,36}]},{'Elixir.Phoenix.LiveView.Utils',to_rendered,2,[{file,"lib/phoenix_live_view/utils.ex"},{line,70}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:45:06.400 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.4976.0>,1,<0.4977.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArithmeticError',message => <<"bad argument in arithmetic expression">>},[{'Elixir.RailwayUiWeb.MessageView','pagination.html',1,[{file,"lib/railway_ui_web/templates/message/pagination.html.leex"},{line,4}]},{'Elixir.RailwayUiWeb.MessageView','index.html',1,[{file,"lib/railway_ui_web/templates/message/index.html.leex"},{line,36}]},{'Elixir.Phoenix.LiveView.Utils',...},...]},...},...]},...}}
2019-12-02 14:46:31.615 [error] <0.5039.0>@Elixir.RailwayUiWeb.MessageLive.Index.State:search_results_count:124 gen_server <0.5039.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.MessageLive.Index.State':search_results_count('Elixir.RailwayUi.PublishedMessage', <<"uuid">>, <<"454d45b0-7cf9-44df-aa94-fa1153835e2a">>) line 124
2019-12-02 14:46:31.616 [error] <0.5039.0>@Elixir.RailwayUiWeb.MessageLive.Index.State:search_results_count:124 CRASH REPORT Process <0.5039.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.MessageLive.Index.State':search_results_count('Elixir.RailwayUi.PublishedMessage', <<"uuid">>, <<"454d45b0-7cf9-44df-aa94-fa1153835e2a">>) line 124
2019-12-02 14:46:31.616 [error] <0.512.0>@Elixir.RailwayUiWeb.MessageLive.Index.State:search_results_count:124 Supervisor {<0.512.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.5039.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.MessageLive.Index.State':search_results_count('Elixir.RailwayUi.PublishedMessage', <<"uuid">>, <<"454d45b0-7cf9-44df-aa94-fa1153835e2a">>) line 124 in context child_terminated
2019-12-02 14:47:19.783 [error] <0.5046.0>@Elixir.RailwayUiWeb.MessageLive.Index.State:search_results_count:124 gen_server <0.5046.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.MessageLive.Index.State':search_results_count('Elixir.RailwayUi.PublishedMessage', <<"uuid">>, <<"454d45b0-7cf9-44df-aa94-fa1153835e2a">>) line 124
2019-12-02 14:47:19.784 [error] <0.5046.0>@Elixir.RailwayUiWeb.MessageLive.Index.State:search_results_count:124 CRASH REPORT Process <0.5046.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.MessageLive.Index.State':search_results_count('Elixir.RailwayUi.PublishedMessage', <<"uuid">>, <<"454d45b0-7cf9-44df-aa94-fa1153835e2a">>) line 124
2019-12-02 14:47:19.784 [error] <0.511.0>@Elixir.RailwayUiWeb.MessageLive.Index.State:search_results_count:124 Supervisor {<0.511.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.5046.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.MessageLive.Index.State':search_results_count('Elixir.RailwayUi.PublishedMessage', <<"uuid">>, <<"454d45b0-7cf9-44df-aa94-fa1153835e2a">>) line 124 in context child_terminated
2019-12-02 14:48:20.507 [error] <0.5083.0> CRASH REPORT Process <0.5083.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => search_results_count,message => nil,module => nil,reason => nil},[{nil,search_results_count,[<<"message_type">>,<<"CreateBatch">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',search_results_count,3,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,126}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',for_search,4,[{file,"lib/railway_ui_web/live/message_live/index/stat..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:48:20.512 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5082.0>,1,<0.5083.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => search_results_count,message => nil,module => nil,reason => nil},[{nil,search_results_count,[<<"message_type">>,<<"CreateBatch">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',search_results_count,3,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,126}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',...},...]},...},...]},...}}
2019-12-02 14:50:07.317 [error] <0.5109.0> CRASH REPORT Process <0.5109.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => search_results_count,message => nil,module => nil,reason => nil},[{nil,search_results_count,[<<"message_type">>,<<"CreateBatch">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',search_results_count,3,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,126}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',for_search,4,[{file,"lib/railway_ui_web/live/message_live/index/stat..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:50:07.323 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5107.0>,1,<0.5109.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => search_results_count,message => nil,module => nil,reason => nil},[{nil,search_results_count,[<<"message_type">>,<<"CreateBatch">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',search_results_count,3,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,126}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',...},...]},...},...]},...}}
2019-12-02 14:51:10.682 [error] <0.5158.0> CRASH REPORT Process <0.5158.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => search_results_count,message => nil,module => nil,reason => nil},[{nil,search_results_count,[<<"message_type">>,<<"CreateBatch">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',search_results_count,3,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,126}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',for_search,4,[{file,"lib/railway_ui_web/live/message_live/index/stat..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:51:10.687 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5157.0>,1,<0.5158.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => search_results_count,message => nil,module => nil,reason => nil},[{nil,search_results_count,[<<"message_type">>,<<"CreateBatch">>],[]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',search_results_count,3,[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,126}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',...},...]},...},...]},...}}
2019-12-02 14:52:53.669 [error] <0.5230.0> CRASH REPORT Process <0.5230.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid result returned from RailwayUiWeb.MessageLive.Index.mount/2.\n\nExpected {:ok, socket} | {:ok, socket, opts}, got: {:ok, [temporary_assigns: [messages: []]]}\n">>},[{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,178}]},{'Elixir.Phoenix.LiveView.Static','call_mount_and_handle_params!',6,[{file,"lib/phoenix_live_view/static.ex"},{line,230}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 14:52:53.684 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5228.0>,1,<0.5230.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"invalid result returned from RailwayUiWeb.MessageLive.Index.mount/2.\n\nExpected {:ok, socket} | {:ok, socket, opts}, got: {:ok, [temporary_assigns: [messages: []]]}\n">>},[{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,178}]},{'Elixir.Phoenix.LiveView.Static','call_mount_and_handle_params!',...},...]},...},...]},...}}
2019-12-02 15:00:23.022 [error] <0.4784.0> gen_server <0.4784.0> terminated with reason: {socket_error,timeout}
2019-12-02 15:00:23.022 [error] <0.4784.0> CRASH REPORT Process <0.4784.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 15:00:23.022 [error] <0.4780.0> gen_server <0.4780.0> terminated with reason: {socket_error,timeout}
2019-12-02 15:00:23.022 [error] <0.4780.0> CRASH REPORT Process <0.4780.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2019-12-02 15:00:23.023 [error] <0.4779.0> Supervisor {<0.4779.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.562>, <0.4780.0>, <0.4782.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65117 -> 127.0.0.1:5672">>) at <0.4784.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 15:00:23.023 [error] <0.4779.0> Supervisor {<0.4779.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.562>, <0.4780.0>, <0.4782.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:65117 -> 127.0.0.1:5672">>) at <0.4784.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 15:00:23.023 [error] <0.4778.0> Supervisor {<0.4778.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.4779.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.4780.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-02 15:00:23.024 [error] <0.4778.0> Supervisor {<0.4778.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.4779.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,2047,0,10,60000,none,[#Fun<am..>,...],...}) at <0.4780.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-02 15:00:23.024 [error] <0.4775.0>@gen_server:call gen_server 'Elixir.RailwayIpc.Connection' terminated with reason: no such process or port in call to gen_server:call(<0.4780.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 15:00:23.025 [error] <0.4775.0>@gen_server:call CRASH REPORT Process 'Elixir.RailwayIpc.Connection' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.4780.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in gen_server:call/3 line 223
2019-12-02 15:00:23.025 [error] <0.424.0>@gen_server:call Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.4775.0> exit with reason no such process or port in call to gen_server:call(<0.4780.0>, {command,{close,{'connection.close',200,<<"Goodbye">>,0,0},60000}}, 60000) in context child_terminated
2019-12-02 15:01:31.782 [error] <0.5410.0> CRASH REPORT Process <0.5410.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => #{name => <<"Sophie">>}},[{'Elixir.Phoenix.LiveView.Plug','-session/2-fun-0-',3,[{file,"lib/phoenix_live_view/plug.ex"},{line,50}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1948}]},{'Elixir.Phoenix.LiveView.Plug',session,2,[{file,"lib/phoenix_live_view/plug.ex"},{line,49}]},{'Elixir.Phoenix.LiveView.Plug',call,2,[{file,"lib/phoenix_live_view/plug.ex"},{line,22}]},{'Elixir.Phoenix.Router',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 15:01:31.794 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5408.0>,1,<0.5410.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => #{name => <<"Sophie">>}},[{'Elixir.Phoenix.LiveView.Plug','-session/2-fun-0-',3,[{file,"lib/phoenix_live_view/plug.ex"},{line,50}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1948}]},{'Elixir.Phoenix.LiveView.Plug',session,2,[{file,"lib/phoenix_live_view/plug.ex"},{line,49}]},{'Elixir.Phoenix.LiveView.Plug',...},...]},...},...]},...}}
2019-12-02 15:12:35.643 [error] <0.5552.0> CRASH REPORT Process <0.5552.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => get_message_type,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State'},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',get_message_type,['Elixir.RailwayUi.PublishedMessage'],[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,133}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',load_messages,1,[{file,"lib/railway_ui_web/live/message_live..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 15:12:35.654 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5550.0>,1,<0.5552.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => get_message_type,kind => nil,module => 'Elixir.RailwayUiWeb.MessageLive.Index.State'},[{'Elixir.RailwayUiWeb.MessageLive.Index.State',get_message_type,['Elixir.RailwayUi.PublishedMessage'],[{file,"lib/railway_ui_web/live/message_live/index/state.ex"},{line,133}]},{'Elixir.RailwayUiWeb.MessageLive.Index.State',...},...]},...},...]},...}}
2019-12-02 15:21:31.306 [error] <0.5709.0> CRASH REPORT Process <0.5709.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @content not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:messages, :socket, :state, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 15:21:31.314 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5707.0>,1,<0.5709.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @content not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:messages, :socket, :state, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-02 15:21:36.291 [error] <0.5725.0> CRASH REPORT Process <0.5725.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @content not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:messages, :socket, :state, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine','fetch_assign!',2,[{file,"lib/phoenix_live_view/engine.ex"},{line,...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 15:21:36.297 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5707.0>,3,<0.5725.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @content not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:messages, :socket, :state, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.LiveView.Engine',...},...]},...},...]},...}}
2019-12-02 15:21:37.653 [error] <0.5742.0> CRASH REPORT Process <0.5742.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"a component RailwayUiWeb.PublishedMessageLive.TableComponent that has implemented handle_event/3 or preload/1 requires an :id assign to be given">>},[{'Elixir.Phoenix.LiveView','__live_component__',3,[{file,"lib/phoenix_live_view.ex"},{line,1156}]},{'Elixir.RailwayUiWeb.MessageView','index.html',1,[{file,"lib/railway_ui_web/templates/message/index.html.leex"},{line,6}]},{'Elixir.Phoenix.LiveView.Utils',to_rendered,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-02 15:21:37.660 [error] <0.389.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.RailwayUiWeb.Endpoint.HTTP',<0.5707.0>,5,<0.5742.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"a component RailwayUiWeb.PublishedMessageLive.TableComponent that has implemented handle_event/3 or preload/1 requires an :id assign to be given">>},[{'Elixir.Phoenix.LiveView','__live_component__',3,[{file,"lib/phoenix_live_view.ex"},{line,1156}]},{'Elixir.RailwayUiWeb.MessageView','index.html',1,[{file,"lib/railway_ui_web/temp..."},...]},...]},...},...]},...}}
2019-12-02 15:21:49.859 [error] <0.5783.0>@Elixir.RailwayUiWeb.PublishedMessageLive.TableComponent:handle_event:12 gen_server <0.5783.0> terminated with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.TableComponent':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"79073780-f742-486d-8e12-8...">>,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{id => <<"blah">>,messages => [...]},...}) line 12
2019-12-02 15:21:49.864 [error] <0.5783.0>@Elixir.RailwayUiWeb.PublishedMessageLive.TableComponent:handle_event:12 CRASH REPORT Process <0.5783.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.TableComponent':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"79073780-f742-486d-8e12-8...">>,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{id => <<"blah">>,messages => [...]},...}) line 12
2019-12-02 15:21:49.864 [error] <0.513.0>@Elixir.RailwayUiWeb.PublishedMessageLive.TableComponent:handle_event:12 Supervisor {<0.513.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.5783.0> exit with reason no function clause matching 'Elixir.RailwayUiWeb.PublishedMessageLive.TableComponent':handle_event(<<"republish">>, #{<<"altKey">> => false,<<"ctrlKey">> => false,<<"message_uuid">> => <<"79073780-f742-486d-8e12-8...">>,...}, #{'__struct__' => 'Elixir.Phoenix.LiveView.Socket',assigns => #{id => <<"blah">>,messages => [...]},...}) line 12 in context child_terminated
2019-12-02 15:23:50.586 [error] <0.424.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.5371.0> exit with reason normal in context child_terminated
2019-12-02 15:23:56.252 [error] <0.424.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.5821.0> exit with reason normal in context child_terminated
2020-04-26 08:08:51.524 [error] <0.593.0> gen_server <0.593.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-04-26 08:08:51.541 [error] <0.593.0> CRASH REPORT Process <0.593.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-04-26 08:08:51.541 [error] <0.444.0> Supervisor {<0.444.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.593.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2020-04-26 08:08:56.951 [error] <0.595.0> gen_server <0.595.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-04-26 08:08:56.953 [error] <0.595.0> CRASH REPORT Process <0.595.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-04-26 08:08:56.953 [error] <0.433.0> Supervisor {<0.433.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.595.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2020-04-26 08:11:14.585 [error] <0.603.0> gen_server <0.603.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-04-26 08:11:14.599 [error] <0.603.0> CRASH REPORT Process <0.603.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-04-26 08:11:14.599 [error] <0.437.0> Supervisor {<0.437.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.603.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
2020-04-26 08:11:36.957 [error] <0.611.0> gen_server <0.611.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-04-26 08:11:36.974 [error] <0.611.0> CRASH REPORT Process <0.611.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2020-04-26 08:11:36.974 [error] <0.442.0> Supervisor {<0.442.0>,'Elixir.Phoenix.Socket.PoolSupervisor.WorkerSupervisor'} had child 'Elixir.Phoenix.Channel.Server' started with {'Elixir.Phoenix.Channel.Server',start_link,undefined} at <0.611.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in context child_terminated
