2019-11-06 08:31:59.818 [error] <0.537.0> CRASH REPORT Process <0.537.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"purpose">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.819 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.819 [error] <0.535.0> CRASH REPORT Process <0.535.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_met...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.537.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.536.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"purpose">> => <<"...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.535.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.499.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_met...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:31:59.860 [error] <0.534.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.498.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:34:48.776 [error] <0.513.0> CRASH REPORT Process <0.513.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:34:48.800 [error] <0.513.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.509.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:00.674 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:00.675 [error] <0.534.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.522.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:07.847 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:07.847 [error] <0.547.0> Cowboy stream 2 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.543.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/css,*/*;q=0.1">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"http_method">> => <<"POST">>,<<"...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:47.236 [error] <0.577.0> CRASH REPORT Process <0.577.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.RailwayUiWeb.ConsumedMessageController',reason => nil},[{'Elixir.RailwayUiWeb.ConsumedMessageController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.RailwayUiWeb.Endpoint',plug_builder_call,2,[{file,"lib/railway_ui_web/endpoint.ex"},{line,1}]},{'Elixir.RailwayUiWeb.Endpoint','call (overridable 3)',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:35:47.237 [error] <0.577.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.575.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.RailwayUiWeb.ConsumedMessageController',reason => nil},[{'Elixir.RailwayUiWeb.ConsumedMessageController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.RailwayUiWeb.Endpoint',plug_builder_call,2,[{file,"lib/railway_ui_web/endpoint.ex"},{line,1}]},{'Elixir.RailwayUiWeb.Endpoint','call (overridable 3)',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:11.768 [error] <0.590.0> CRASH REPORT Process <0.590.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:11.768 [error] <0.590.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.589.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:34.611 [error] <0.617.0> CRASH REPORT Process <0.617.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:34.612 [error] <0.617.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.616.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:38.424 [error] <0.638.0> CRASH REPORT Process <0.638.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:38.425 [error] <0.638.0> Cowboy stream 4 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.616.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:47.193 [error] <0.648.0> CRASH REPORT Process <0.648.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:47.193 [error] <0.648.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.646.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:53.603 [error] <0.667.0> CRASH REPORT Process <0.667.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:36:53.604 [error] <0.667.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.660.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:24.558 [error] <0.525.0> CRASH REPORT Process <0.525.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:24.580 [error] <0.525.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.523.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:32.335 [error] <0.533.0> CRASH REPORT Process <0.533.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:37:32.336 [error] <0.533.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.532.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => all,message => nil,module => 'Elixir.Repo',reason => nil},[{'Elixir.Repo',all,['Elixir.RailwayIpc.Persistence.ConsumedMessage'],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,5}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controlle..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:36.326 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:36.340 [error] <0.649.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.648.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:40.275 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:40.275 [error] <0.664.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.648.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => all,message => nil,module => 'Elixir.RailwayUi.ConsumedMessage',reason => nil},[{'Elixir.RailwayUi.ConsumedMessage',all,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:56.124 [error] <0.674.0> CRASH REPORT Process <0.674.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => get_consumed_messages,message => nil,module => nil,reason => nil},[{nil,get_consumed_messages,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,1}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:43:56.124 [error] <0.674.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.673.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => get_consumed_messages,message => nil,module => nil,reason => nil},[{nil,get_consumed_messages,[],[]},{'Elixir.RailwayUiWeb.ConsumedMessageController',index,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,7}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',action,2,[{file,"lib/railway_ui_web/controllers/consumed_message_controller.ex"},{line,1}]},{'Elixir.RailwayUiWeb.ConsumedMessageController',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:45:39.304 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_messages_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_messages_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:45:39.304 [error] <0.753.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.751.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => published_messages_path,message => nil,module => 'Elixir.RailwayUiWeb.Router.Helpers',reason => nil},[{'Elixir.RailwayUiWeb.Router.Helpers',published_messages_path,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:25.000 [error] <0.790.0> CRASH REPORT Process <0.790.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:25.010 [error] <0.790.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.789.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:32.811 [error] <0.811.0> CRASH REPORT Process <0.811.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:32.812 [error] <0.811.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.810.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:33.670 [error] <0.830.0> CRASH REPORT Process <0.830.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-06 08:59:33.672 [error] <0.830.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.810.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @messages not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:conn, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,133}]},{'Elixir.RailwayUiWeb.PageView',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-12 08:42:53.761 [error] <0.49.0> Loading of /Users/sophie.debenedetto/Dev/railway_hex/railway_ui/_build/test/lib/jason/ebin/Elixir.JASON.beam failed: badfile
2019-11-12 08:42:53.761 [error] emulator beam/beam_load.c(1433): Error loading module 'Elixir.JASON':
  BEAM file exists but it defines a module named Elixir.Jason

2019-12-11 09:40:22.837 [error] <0.507.0> gen_server <0.507.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:40:22.838 [error] <0.508.0> gen_server <0.508.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:40:22.838 [error] <0.508.0> CRASH REPORT Process <0.508.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393 in 'Elixir.Connection':enter_stop/5 line 686
2019-12-11 09:40:22.838 [error] <0.509.0> gen_server <0.509.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:40:22.839 [error] <0.510.0> gen_server <0.510.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:40:22.839 [error] <0.511.0> gen_server <0.511.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:40:22.839 [error] <0.512.0> gen_server <0.512.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:09.381 [error] <0.511.0> gen_server <0.511.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:09.381 [error] <0.507.0> gen_server <0.507.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:09.382 [error] <0.507.0> CRASH REPORT Process <0.507.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393 in 'Elixir.Connection':enter_stop/5 line 686
2019-12-11 09:45:09.382 [error] <0.508.0> gen_server <0.508.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:09.382 [error] <0.514.0> gen_server <0.514.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:09.382 [error] <0.511.0> CRASH REPORT Process <0.511.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393 in 'Elixir.Connection':enter_stop/5 line 686
2019-12-11 09:45:09.383 [error] <0.515.0> gen_server <0.515.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:21.244 [error] <0.507.0> gen_server <0.507.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:21.244 [error] <0.508.0> gen_server <0.508.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:21.244 [error] <0.509.0> gen_server <0.509.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:21.244 [error] <0.510.0> gen_server <0.510.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:21.245 [error] <0.511.0> gen_server <0.511.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:21.245 [error] <0.508.0> CRASH REPORT Process <0.508.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393 in 'Elixir.Connection':enter_stop/5 line 686
2019-12-11 09:45:21.245 [error] <0.510.0> CRASH REPORT Process <0.510.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393 in 'Elixir.Connection':enter_stop/5 line 686
2019-12-11 09:45:21.245 [error] <0.512.0> gen_server <0.512.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.558 [error] <0.372.0> gen_server <0.372.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.558 [error] <0.373.0> gen_server <0.373.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.559 [error] <0.378.0> gen_server <0.378.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.559 [error] <0.377.0> gen_server <0.377.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.559 [error] <0.379.0> gen_server <0.379.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.559 [error] <0.381.0> gen_server <0.381.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.559 [error] <0.374.0> gen_server <0.374.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.560 [error] <0.375.0> gen_server <0.375.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.560 [error] <0.376.0> gen_server <0.376.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:45:52.560 [error] <0.380.0> gen_server <0.380.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details">>} in 'Elixir.Keyword':'fetch!'/2 line 393
2019-12-11 09:48:53.349 [error] <0.4627.0> CRASH REPORT Process <0.4627.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"Upgrade">>,<<"cookie">> => <<"_course_conductor_key=SFMyNTY.g3QAAAADbQAAAAVhZG1pbmQABHRy...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 09:48:53.358 [error] <0.4627.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.4626.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"Upgrade">>,<<"cookie">> => <<"_course_conductor_key=SFMyNTY.g3QAAAADbQAAAAVhZG1pbmQABHRy...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 09:49:05.197 [error] <0.4644.0> CRASH REPORT Process <0.4644.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.published_message_path/3 and action :republish. The following actions/clauses are supported:\n\n    published_message_path(conn_or_endpoint, :index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.PublishedMessageView','-index.html/1-fun-0-',3,[{file,"lib/railway..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 09:49:05.197 [error] <0.4644.0> Cowboy stream 3 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.4635.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"no function clause for RailwayUiWeb.Router.Helpers.published_message_path/3 and action :republish. The following actions/clauses are supported:\n\n    published_message_path(conn_or_endpoint, :index, params \\\\ [])">>},[{'Elixir.Phoenix.Router.Helpers',raise_route_error,6,[{file,"lib/phoenix/router/helpers.ex"},{line,346}]},{'Elixir.RailwayUiWeb.PublishedMessageView','-index.html/1-fun-0-',3,[{file,"lib/railway..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 09:51:05.344 [error] <0.4702.0> CRASH REPORT Process <0.4702.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"c...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 09:51:05.345 [error] <0.4702.0> Cowboy stream 1 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.4700.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"c...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 09:51:40.253 [error] <0.4732.0> CRASH REPORT Process <0.4732.0> with 0 neighbours exited with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 81,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 09:51:40.254 [error] <0.4732.0> Cowboy stream 5 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.4704.0> had its request process exit with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 81,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 10:09:49.679 [error] <0.996.0> CRASH REPORT Process <0.996.0> with 0 neighbours exited with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 83,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 10:09:49.714 [error] <0.996.0> Cowboy stream 5 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.977.0> had its request process exit with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 83,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 10:12:00.159 [error] <0.759.0> CRASH REPORT Process <0.759.0> with 0 neighbours exited with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 81,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 10:12:00.171 [error] <0.759.0> Cowboy stream 7 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.726.0> had its request process exit with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 81,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 10:13:10.785 [error] <0.422.0> CRASH REPORT Process <0.422.0> with 0 neighbours exited with reason: {{already_started,<0.437.0>},{'Elixir.RailwayIpc.Application',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-11 10:13:49.578 [error] <0.732.0> Supervisor 'Elixir.RailwayUi.Supervisor' had child 'Elixir.RailwayUi.Repo' started with 'Elixir.RailwayUi.Repo':start_link([]) at undefined exit with reason {already_started,<0.679.0>} in context start_error
2019-12-11 10:13:49.579 [error] <0.730.0> CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.RailwayUi.Repo',{already_started,<0.679.0>}}},{'Elixir.RailwayUi.Application',start,[normal,[]]}} in application_master:init/4 line 138
2019-12-11 10:14:57.660 [error] <0.565.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.566.0> exit with reason normal in context child_terminated
2019-12-11 10:15:52.638 [error] <0.787.0> gen_server 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:15:52.640 [error] <0.787.0> CRASH REPORT Process 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:15:52.640 [error] <0.786.0> Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' started with 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer':start_link([]) at <0.787.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948 in context child_terminated
2019-12-11 10:16:34.075 [error] <0.883.0> CRASH REPORT Process <0.883.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => invoke_republish_message,kind => nil,module => 'Elixir.RailwayIpc.Ipc.RepublishedMessagesPublisher'},[{'Elixir.RailwayIpc.Ipc.RepublishedMessagesPublisher',invoke_republish_message,[<<"79c17648-6cac-484a-911c-184b6be71bfa">>,#{}],[{file,"lib/railway_ipc/ipc/publishers/republished_messages_publisher.ex"},{line,9}]},{'Elixir.RailwayUiWeb.PublishedMessageController',republish,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 10:16:34.086 [error] <0.883.0> Cowboy stream 4 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.862.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => invoke_republish_message,kind => nil,module => 'Elixir.RailwayIpc.Ipc.RepublishedMessagesPublisher'},[{'Elixir.RailwayIpc.Ipc.RepublishedMessagesPublisher',invoke_republish_message,[<<"79c17648-6cac-484a-911c-184b6be71bfa">>,#{}],[{file,"lib/railway_ipc/ipc/publishers/republished_messages_publisher.ex"},{line,9}]},{'Elixir.RailwayUiWeb.PublishedMessageController',republish,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 10:17:05.537 [error] <0.920.0> CRASH REPORT Process <0.920.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protobuf.InvalidError',message => <<"RailwayIpc.Commands.RepublishMessage#user_uuid is invalid!">>},[{'Elixir.Protobuf.Validator','validate!',1,[{file,"lib/protobuf/validator.ex"},{line,5}]},{'Elixir.Protobuf.Encoder',encode,2,[{file,"lib/protobuf/encoder.ex"},{line,9}]},{'Elixir.RailwayIpc.Core.Payload',encode_message,1,[{file,"lib/railway_ipc/core/payload.ex"},{line,46}]},{'Elixir.RailwayIpc.Core.Payload',encode,1,[{file,"lib/railway_ip..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 10:17:05.538 [error] <0.920.0> Cowboy stream 6 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.894.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protobuf.InvalidError',message => <<"RailwayIpc.Commands.RepublishMessage#user_uuid is invalid!">>},[{'Elixir.Protobuf.Validator','validate!',1,[{file,"lib/protobuf/validator.ex"},{line,5}]},{'Elixir.Protobuf.Encoder',encode,2,[{file,"lib/protobuf/encoder.ex"},{line,9}]},{'Elixir.RailwayIpc.Core.Payload',encode_message,1,[{file,"lib/railway_ipc/core/payload.ex"},{line,46}]},{'Elixir.RailwayIpc.Core.Payload',encode,1,[{file,"lib/railway_ip..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 10:21:50.825 [error] <0.993.0> CRASH REPORT Process <0.993.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => invoke_republish_message,kind => nil,module => 'Elixir.RailwayIpc.Ipc.RepublishedMessagesPublisher'},[{'Elixir.RailwayIpc.Ipc.RepublishedMessagesPublisher',invoke_republish_message,[<<"79c17648-6cac-484a-911c-184b6be71bfa">>,#{}],[{file,"lib/railway_ipc/ipc/publishers/republished_messages_publisher.ex"},{line,9}]},{'Elixir.RailwayUiWeb.PublishedMessageController',republish,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 10:21:50.826 [error] <0.993.0> Cowboy stream 4 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.972.0> had its request process exit with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => invoke_republish_message,kind => nil,module => 'Elixir.RailwayIpc.Ipc.RepublishedMessagesPublisher'},[{'Elixir.RailwayIpc.Ipc.RepublishedMessagesPublisher',invoke_republish_message,[<<"79c17648-6cac-484a-911c-184b6be71bfa">>,#{}],[{file,"lib/railway_ipc/ipc/publishers/republished_messages_publisher.ex"},{line,9}]},{'Elixir.RailwayUiWeb.PublishedMessageController',republish,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-12-11 10:22:01.932 [error] <0.433.0> gen_server 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:22:01.933 [error] <0.433.0> CRASH REPORT Process 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:22:01.934 [error] <0.432.0> Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' started with 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer':start_link([]) at <0.433.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948 in context child_terminated
2019-12-11 10:23:42.110 [error] <0.433.0> gen_server 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:23:42.112 [error] <0.433.0> CRASH REPORT Process 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:23:42.112 [error] <0.432.0> Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' started with 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer':start_link([]) at <0.433.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948 in context child_terminated
2019-12-11 10:32:23.132 [error] <0.438.0> gen_server 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:32:23.135 [error] <0.438.0> CRASH REPORT Process 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:32:23.136 [error] <0.437.0> Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' started with 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer':start_link([]) at <0.438.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948 in context child_terminated
2019-12-11 10:34:11.725 [error] <0.498.0> gen_server <0.498.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2019-12-11 10:34:11.742 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2019-12-11 10:34:11.743 [error] <0.497.0> Supervisor {<0.497.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55645 -> 127.0.0.1:5672">>,2}) at <0.498.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2019-12-11 10:34:11.743 [error] <0.497.0> Supervisor {<0.497.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55645 -> 127.0.0.1:5672">>,2}) at <0.498.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-11 10:34:11.743 [error] <0.499.0> gen_server <0.499.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.498.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-KjytbMznObRH7kFpdVlsEQ">>,2,false,<<>>,<<"railway_ipc:republished_messages:commands">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"{\"encoded_message\":\"CiQxZjRjNDA1MS1mZTEyLTQxY2YtYTM5YS00OWY3OTRmNmIzMzMSJDJlMTk4MWY1LTExMWYtNDg3NS1iMzUxLTRiZWY0ZDI4MjU5ORokN2U4N2I5ZjE...">>}},...]}} in gen_server2:call/3 line 346
2019-12-11 10:34:11.748 [error] <0.435.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.436.0> exit with reason normal in context child_terminated
2019-12-11 10:34:11.786 [error] <0.764.0> gen_server 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:34:11.787 [error] <0.764.0> CRASH REPORT Process 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:34:11.787 [error] <0.763.0> Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' started with 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer':start_link([]) at <0.764.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948 in context child_terminated
2019-12-11 10:35:47.010 [error] <0.779.0> gen_server <0.779.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2019-12-11 10:35:47.011 [error] <0.779.0> CRASH REPORT Process <0.779.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2019-12-11 10:35:47.012 [error] <0.778.0> Supervisor {<0.778.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55753 -> 127.0.0.1:5672">>,2}) at <0.779.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2019-12-11 10:35:47.012 [error] <0.778.0> Supervisor {<0.778.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55753 -> 127.0.0.1:5672">>,2}) at <0.779.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-11 10:35:47.013 [error] <0.780.0> gen_server <0.780.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.779.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-eZ39g9uVZQEATDI9UMTTJw">>,3,false,<<>>,<<"railway_ipc:republished_messages:commands">>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"{\"encoded_message\":\"CiQxZjRjNDA1MS1mZTEyLTQxY2YtYTM5YS00OWY3OTRmNmIzMzMSJGNhYzcyYzJkLTQxZjgtNGI4OC1hNjMwLTA4MDczYWRlNWVkMRokNmQzYmZhYTM...">>}},...]}} in gen_server2:call/3 line 346
2019-12-11 10:35:47.025 [error] <0.435.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.762.0> exit with reason normal in context child_terminated
2019-12-11 10:35:47.077 [error] <0.800.0> gen_server 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:35:47.079 [error] <0.800.0> CRASH REPORT Process 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948
2019-12-11 10:35:47.079 [error] <0.799.0> Supervisor 'Elixir.RailwayIpc.Consumer.Supervisor' had child 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer' started with 'Elixir.RailwayIpc.Ipc.RepublishedMessagesConsumer':start_link([]) at <0.800.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Ecto.Query.CastError',message => <<"/Users/sophie.debenedetto/Dev/railway_hex/railway_ipc/lib/railway_ipc/persistence.ex:50: value `\"1234\"` cannot be dumped to type :binary_id in query:\n\nfrom p0 in RailwayIpc.Persistence.PublishedMessage,\n  where: p0.uuid == ^\"1234\",\n  select: p0\n">>,type => binary_id,value => <<"1234">>} in 'Elixir.Enum':'-reduce/3-lists^foldl/2-0-'/3 line 1948 in context child_terminated
2019-12-11 12:01:10.405 [error] <0.602.0> CRASH REPORT Process <0.602.0> with 0 neighbours exited with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 85,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 12:01:10.469 [error] <0.602.0> Cowboy stream 4 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.587.0> had its request process exit with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 85,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 12:01:45.652 [error] <0.746.0> CRASH REPORT Process <0.746.0> with 0 neighbours exited with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 81,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 12:01:45.667 [error] <0.746.0> Cowboy stream 4 with ranch listener 'Elixir.RailwayUiWeb.Endpoint.HTTP' and connection process <0.727.0> had its request process exit with reason: {{noproc,{'Elixir.GenServer',call,['Elixir.RailwayIpc.Connection',publisher_channel,5000]}},{'Elixir.RailwayUiWeb.Endpoint',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 81,cert => undefined,has_body => true,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-l...">> => ...,...},...}},...},...]}} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 67
2019-12-11 12:03:08.729 [error] <0.4457.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.4458.0> exit with reason normal in context child_terminated
2019-12-11 12:03:12.564 [error] <0.4457.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.4671.0> exit with reason normal in context child_terminated
2019-12-11 12:09:19.478 [error] <0.804.0> Supervisor 'Elixir.RailwayIpc.Connection.Supervisor' had child 'Elixir.RailwayIpc.Connection' started with 'Elixir.RailwayIpc.Connection':start_link([{name,'Elixir.RailwayIpc.Connection'}]) at <0.805.0> exit with reason normal in context child_terminated
